/**
 * `GET /sw.js` — service worker, served from a route handler so its cached
 * URLs are templated with the runtime `BASE_PATH`.
 *
 * Why a route instead of `public/sw.js`:
 *   Next.js bakes `basePath`/`assetPrefix` at BUILD time, but a single image
 *   must serve any slug chosen at RUNTIME (k3s) AND the default root
 *   (single-host prod). A static `public/sw.js` can't read the runtime prefix:
 *   hardcoding `/` breaks slug instances, and the build-time sentinel approach
 *   (used for the rest of the static tree) breaks root, because the container
 *   entrypoint materialization that rewrites the sentinel never runs on the
 *   single-host prod deploy. Serving the SW from this handler lets us
 *   interpolate the server-side `BASE_PATH` (read at process start by
 *   `@/lib/base-path`) so the cached URLs are correct in BOTH modes with no
 *   build-time baking and no boot-time rewrite:
 *     - root  (BASE_PATH === ""):     `/`, `/manifest.json`, `/icons/...`
 *     - slug  (BASE_PATH === "/alpha"): `/alpha/`, `/alpha/manifest.json`, ...
 *
 * Next automatically prefixes this route's PATH with the build `basePath`
 * (so it is served at `/sw.js` at root and `/alpha/sw.js` under a slug). The
 * registration component (`ServiceWorkerRegistration`) registers it at
 * `${runtimeBasePath()}/sw.js` with a matching `${prefix}/` scope.
 */

import { BASE_PATH } from "@/lib/base-path";

// The SW body must be templated per-request from the runtime BASE_PATH; never
// statically optimized. (BASE_PATH is fixed for the process lifetime, but
// force-dynamic keeps the no-cache contract explicit and avoids any build-time
// snapshotting of the response.)
export const dynamic = "force-dynamic";

/**
 * Build the service-worker source with `BASE_PATH`-prefixed cache URLs.
 * `BASE_PATH` is "" at root or e.g. "/alpha" under a slug, so `${BASE_PATH}/`
 * is "/" or "/alpha/" — exactly the app shell URL the SW should cache and use
 * as the offline-navigation fallback.
 *
 * Exported (and parameterized on `basePath`) so the unit test can assert the
 * emitted cache URLs for root and slug without spinning up a request.
 */
export function serviceWorkerSource(basePath: string): string {
  // JSON.stringify is the escape boundary for embedding the prefix into JS
  // source — basePath is validated upstream (`/[a-z0-9-]` segments) but we
  // never string-concatenate it raw into emitted code.
  const PREFIX = JSON.stringify(basePath);
  return `// Service worker — generated by src/app/sw.js/route.ts.
// Cache URLs are templated from the server-side runtime BASE_PATH so the SW is
// correct at root (single-host prod) AND under a slug (k3s) with no build-time
// baking. BASE_PREFIX is "" at root or e.g. "/alpha" under a slug.
const BASE_PREFIX = ${PREFIX};
const CACHE_NAME = 'remote-dev-v1';
const STATIC_ASSETS = [
  \`\${BASE_PREFIX}/\`,
  \`\${BASE_PREFIX}/manifest.json\`,
  \`\${BASE_PREFIX}/icons/icon-192x192.png\`,
  \`\${BASE_PREFIX}/icons/icon-512x512.png\`,
];

// Install: cache static assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(STATIC_ASSETS);
    })
  );
  self.skipWaiting();
});

// Activate: clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      );
    })
  );
  self.clients.claim();
});

// Fetch: network-first for API/WebSocket, cache-first for static assets
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Skip WebSocket and API requests - these must be online
  if (
    request.url.includes('/api/') ||
    request.url.startsWith('ws://') ||
    request.url.startsWith('wss://')
  ) {
    return;
  }

  // For navigation requests, try network first, fall back to cache
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Cache successful navigation responses
          if (response.ok) {
            const responseClone = response.clone();
            caches.open(CACHE_NAME).then((cache) => {
              cache.put(request, responseClone);
            });
          }
          return response;
        })
        .catch(async () => {
          // Offline: try to serve from cache, falling back to the app shell.
          // \`\${BASE_PREFIX}/\` is the instance's app-shell URL.
          const cached = await caches.match(request);
          return cached || caches.match(\`\${BASE_PREFIX}/\`);
        })
    );
    return;
  }

  // For static assets, use cache-first strategy
  if (
    request.destination === 'image' ||
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'font'
  ) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) {
          // Return cached, but update in background
          fetch(request)
            .then((response) => {
              if (response.ok) {
                caches.open(CACHE_NAME).then((cache) => {
                  cache.put(request, response);
                });
              }
            })
            .catch(() => {
              // Network error during background update, ignore silently
            });
          return cached;
        }
        // Not cached, fetch and cache
        return fetch(request).then((response) => {
          if (response.ok) {
            const responseClone = response.clone();
            caches.open(CACHE_NAME).then((cache) => {
              cache.put(request, responseClone);
            });
          }
          return response;
        });
      })
    );
    return;
  }

  // Default: network with cache fallback
  event.respondWith(
    fetch(request).catch(() => caches.match(request))
  );
});
`;
}

export function GET(): Response {
  return new Response(serviceWorkerSource(BASE_PATH), {
    status: 200,
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // SW updates must propagate quickly; never let a CDN/browser pin a stale
      // worker. The browser still byte-compares on its hourly update check.
      "Cache-Control": "no-cache",
    },
  });
}
