/**
 * Provisioner service (spec §6.4, §15 B2) — the transactional orchestration over
 * the pure builders in `provisioner-builders.ts`.
 *
 * The k8s clients are DEPENDENCY-INJECTED ({@link K8sClients}) so this module is
 * unit-testable with mocks and never imports a live cluster at module load.
 *
 * Create order (§6.4): Namespace → Secret `rdv-shared` → Secret `rdv-<slug>` →
 * Service `rdv` → StatefulSet (+ optional seed Job). On the FIRST error, the
 * whole instance is rolled back by deleting the namespace (atomic cascade,
 * §15 B2) and a typed {@link ProvisioningError} is rethrown.
 *
 * Idempotency: a 409 AlreadyExists for any object is treated as success per
 * object, so a retried reconcile after a partial create does not fail just
 * because the namespace (or another object) already exists.
 */

import { ApiException } from "@kubernetes/client-node";
import type { CoreV1Api, AppsV1Api, BatchV1Api } from "@kubernetes/client-node";
import type { InstanceRow } from "@/db/schema";
import { namespaceForSlug } from "@/lib/slug";
import {
  getCoreV1Api,
  getAppsV1Api,
  getBatchV1Api,
} from "@/lib/k8s";
import {
  buildNamespace,
  buildSharedSecret,
  buildAuthSecret,
  buildService,
  buildStatefulSet,
  buildInstanceEnv,
  SERVICE_NAME,
} from "@/lib/provisioner-builders";
import {
  toVolumeClaimTemplate,
  type ResolvedStorageTarget,
} from "@/lib/storage";
import { createLogger } from "@/lib/logger";

const log = createLogger("Provisioner");

/** The k8s clients the provisioner needs, injected for testability. */
export interface K8sClients {
  core: CoreV1Api;
  apps: AppsV1Api;
  batch: BatchV1Api;
}

/** Real clients (lazy; throws if no cluster — callers guard for that). */
export function defaultClients(): K8sClients {
  return {
    core: getCoreV1Api(),
    apps: getAppsV1Api(),
    batch: getBatchV1Api(),
  };
}

/** The stage at which provisioning failed (for the audit log / error message). */
export type ProvisioningStage =
  | "namespace"
  | "shared-secret"
  | "auth-secret"
  | "service"
  | "statefulset";

/** Typed error carrying the failing stage + the underlying cause. */
export class ProvisioningError extends Error {
  constructor(
    readonly stage: ProvisioningStage,
    readonly cause: unknown,
  ) {
    super(`Provisioning failed at stage "${stage}": ${String(cause)}`);
    this.name = "ProvisioningError";
  }
}

/** HTTP status of an ApiException, or undefined for non-API errors. */
function statusCode(err: unknown): number | undefined {
  return err instanceof ApiException ? err.code : undefined;
}

function isAlreadyExists(err: unknown): boolean {
  return statusCode(err) === 409;
}

function isNotFound(err: unknown): boolean {
  return statusCode(err) === 404;
}

/**
 * Run one create step. A 409 AlreadyExists is swallowed (idempotent retry);
 * any other error is wrapped in a {@link ProvisioningError} for the given stage.
 */
async function createStep(
  stage: ProvisioningStage,
  fn: () => Promise<unknown>,
): Promise<void> {
  try {
    await fn();
  } catch (err) {
    if (isAlreadyExists(err)) {
      log.debug("object already exists (treated as success)", { stage });
      return;
    }
    throw new ProvisioningError(stage, err);
  }
}

/** Options that parameterise provisioning beyond what's on the instance row. */
export interface ProvisionOptions {
  /** Slug-aware GHCR image:sha the StatefulSet runs (SUPERVISOR_INSTANCE_IMAGE). */
  image: string;
  /** External host instances are served under (SUPERVISOR_INSTANCE_HOST). */
  host: string;
  /** Resolved storage target (default resolver in Phase 1). */
  storage: ResolvedStorageTarget;
  /** UNIQUE per-instance AUTH_SECRET — generated by the reconciler, never logged. */
  authSecret: string;
  /** Cloudflare Access tags shared across the instance pods. */
  cfAccess: { team: string; aud: string };
  /** Optional GitHub OAuth creds for the instance. */
  github?: { clientId: string; clientSecret: string };
  // NOTE: first-boot seed emails are intentionally NOT a provisioning input in
  // Phase 1 — the seed Job dispatch is deferred to Phase 2 (jvcx.8). See the
  // comment at the end of provisionInstance.
}

/**
 * Provision an instance transactionally (§6.4). Creates objects in order; on the
 * first failure, deletes the namespace (cascade rollback) and rethrows a
 * {@link ProvisioningError}.
 */
export async function provisionInstance(
  row: InstanceRow,
  opts: ProvisionOptions,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const { slug } = row;
  const namespace = namespaceForSlug(slug);
  const { core, apps } = clients;

  log.info("provisioning instance", { slug, namespace, image: opts.image });

  try {
    // 1. Namespace.
    await createStep("namespace", () =>
      core.createNamespace({ body: buildNamespace(slug) }),
    );

    // 2. Shared (CF Access) secret.
    await createStep("shared-secret", () =>
      core.createNamespacedSecret({
        namespace,
        body: buildSharedSecret(slug, {
          cfAccessTeam: opts.cfAccess.team,
          cfAccessAud: opts.cfAccess.aud,
        }),
      }),
    );

    // 3. Per-instance auth secret (UNIQUE AUTH_SECRET, optional GitHub).
    await createStep("auth-secret", () =>
      core.createNamespacedSecret({
        namespace,
        body: buildAuthSecret(slug, {
          authSecret: opts.authSecret,
          github: opts.github,
        }),
      }),
    );

    // 4. Governing Service `rdv`.
    await createStep("service", () =>
      core.createNamespacedService({ namespace, body: buildService(slug) }),
    );

    // 5. StatefulSet.
    const env = buildInstanceEnv(slug, { host: opts.host });
    await createStep("statefulset", () =>
      apps.createNamespacedStatefulSet({
        namespace,
        body: buildStatefulSet(slug, {
          image: opts.image,
          env,
          volumeClaimTemplate: toVolumeClaimTemplate(opts.storage),
          withGithub: Boolean(opts.github),
        }),
      }),
    );

    // 6. First-boot seed Job — DEFERRED to Phase 2.
    // TODO(jvcx.8): seed must run over HTTP against the ready instance (the RWO
    // PVC can't be co-mounted by a Job while the StatefulSet pod holds it, and
    // `bun run db:seed` talks to the running instance). The builder
    // (buildSeedJob) stays, but provisioning does NOT dispatch it in Phase 1.

    log.info("provisioning succeeded", { slug, namespace });
  } catch (err) {
    // Roll back: delete the namespace (cascade). Best-effort — log if cleanup
    // itself fails, but always rethrow the ORIGINAL provisioning error.
    const stage = err instanceof ProvisioningError ? err.stage : "unknown";
    log.error("provisioning failed; rolling back namespace", {
      slug,
      namespace,
      stage,
      error: String(err),
    });
    try {
      await terminateInstance(slug, clients);
    } catch (rollbackErr) {
      log.error("rollback (namespace delete) failed", {
        slug,
        namespace,
        error: String(rollbackErr),
      });
    }
    throw err;
  }
}

/**
 * Readiness check: StatefulSet `readyReplicas >= 1`.
 *
 * Design (per spec): we gate on `readyReplicas` rather than issuing an in-pod
 * HTTP `GET /<slug>/api/readyz` from the controller. `readyReplicas` is a sound
 * proxy because it ALREADY requires the pod's own readiness probe — which is
 * exactly `GET /<slug>/api/readyz` on 6001 (see buildStatefulSet) — to pass.
 * This avoids the controller needing cluster-DNS reachability to each pod.
 * TODO(jvcx.5+): optionally add a direct HTTP readyz poll via cluster DNS for a
 * second signal once the router/DNS path is exercised end-to-end.
 *
 * A 404 (StatefulSet not yet visible) is reported as not-ready, not an error.
 */
export async function checkInstanceReady(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<{ ready: boolean; reason?: string }> {
  const namespace = namespaceForSlug(slug);
  try {
    const sts = await clients.apps.readNamespacedStatefulSet({
      name: SERVICE_NAME,
      namespace,
    });
    const ready = sts.status?.readyReplicas ?? 0;
    if (ready >= 1) return { ready: true };
    return { ready: false, reason: `readyReplicas=${ready}` };
  } catch (err) {
    if (isNotFound(err)) {
      return { ready: false, reason: "statefulset-not-found" };
    }
    // Transient read error — report not-ready (caller decides on timeout).
    return { ready: false, reason: `read-error: ${String(err)}` };
  }
}

/**
 * Terminate an instance: delete its namespace `rdv-<slug>` (cascade). A 404
 * NotFound means the namespace is already gone — treated as success.
 */
export async function terminateInstance(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const namespace = namespaceForSlug(slug);
  try {
    await clients.core.deleteNamespace({ name: namespace });
    log.info("namespace delete requested", { slug, namespace });
  } catch (err) {
    if (isNotFound(err)) {
      log.debug("namespace already gone (treated as success)", {
        slug,
        namespace,
      });
      return;
    }
    throw err;
  }
}

/**
 * True if the instance's namespace currently exists. A 404 → false; any other
 * error propagates (the caller treats an unknown cluster error as "unknown",
 * not "gone").
 */
export async function namespaceExists(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<boolean> {
  const namespace = namespaceForSlug(slug);
  try {
    await clients.core.readNamespace({ name: namespace });
    return true;
  } catch (err) {
    if (isNotFound(err)) return false;
    throw err;
  }
}
