/**
 * Provisioner service (spec §6.4, §15 B2) — the transactional orchestration over
 * the pure builders in `provisioner-builders.ts`.
 *
 * The k8s clients are DEPENDENCY-INJECTED ({@link K8sClients}) so this module is
 * unit-testable with mocks and never imports a live cluster at module load.
 *
 * Create order (§6.4): Namespace → Secret `rdv-shared` → Secret `rdv-<slug>` →
 * Service `rdv` → StatefulSet (+ optional seed Job). On the FIRST error, the
 * whole instance is rolled back by deleting the namespace (atomic cascade,
 * §15 B2) and a typed {@link ProvisioningError} is rethrown.
 *
 * Idempotency: a 409 AlreadyExists for any object is treated as success per
 * object, so a retried reconcile after a partial create does not fail just
 * because the namespace (or another object) already exists.
 */

import { ApiException } from "@kubernetes/client-node";
import type { CoreV1Api, AppsV1Api, BatchV1Api } from "@kubernetes/client-node";
import type { InstanceRow } from "@/db/schema";
import { namespaceForSlug } from "@/lib/slug";
import {
  getCoreV1Api,
  getAppsV1Api,
  getBatchV1Api,
} from "@/lib/k8s";
import {
  buildNamespace,
  buildSharedSecret,
  buildAuthSecret,
  buildImagePullSecret,
  buildService,
  buildStatefulSet,
  buildInstanceEnv,
  SERVICE_NAME,
} from "@/lib/provisioner-builders";
import { DATA_VOLUME_NAME } from "@/lib/storage";
import {
  toVolumeClaimTemplate,
  type ResolvedStorageTarget,
} from "@/lib/storage";
import { createLogger } from "@/lib/logger";

const log = createLogger("Provisioner");

/** The k8s clients the provisioner needs, injected for testability. */
export interface K8sClients {
  core: CoreV1Api;
  apps: AppsV1Api;
  batch: BatchV1Api;
}

/** Real clients (lazy; throws if no cluster — callers guard for that). */
export function defaultClients(): K8sClients {
  return {
    core: getCoreV1Api(),
    apps: getAppsV1Api(),
    batch: getBatchV1Api(),
  };
}

/** The stage at which provisioning failed (for the audit log / error message). */
export type ProvisioningStage =
  | "namespace"
  | "image-pull-secret"
  | "shared-secret"
  | "auth-secret"
  | "service"
  | "statefulset";

/** Typed error carrying the failing stage + the underlying cause. */
export class ProvisioningError extends Error {
  constructor(
    readonly stage: ProvisioningStage,
    readonly cause: unknown,
  ) {
    super(`Provisioning failed at stage "${stage}": ${String(cause)}`);
    this.name = "ProvisioningError";
  }
}

/** HTTP status of an ApiException, or undefined for non-API errors. */
function statusCode(err: unknown): number | undefined {
  return err instanceof ApiException ? err.code : undefined;
}

function isAlreadyExists(err: unknown): boolean {
  return statusCode(err) === 409;
}

function isNotFound(err: unknown): boolean {
  return statusCode(err) === 404;
}

/**
 * Run one create step. A 409 AlreadyExists is swallowed (idempotent retry);
 * any other error is wrapped in a {@link ProvisioningError} for the given stage.
 */
async function createStep(
  stage: ProvisioningStage,
  fn: () => Promise<unknown>,
): Promise<void> {
  try {
    await fn();
  } catch (err) {
    if (isAlreadyExists(err)) {
      log.debug("object already exists (treated as success)", { stage });
      return;
    }
    throw new ProvisioningError(stage, err);
  }
}

/** Options that parameterise provisioning beyond what's on the instance row. */
export interface ProvisionOptions {
  /** Slug-aware GHCR image:sha the StatefulSet runs (SUPERVISOR_INSTANCE_IMAGE). */
  image: string;
  /** External host instances are served under (SUPERVISOR_INSTANCE_HOST). */
  host: string;
  /** Resolved storage target (default resolver in Phase 1). */
  storage: ResolvedStorageTarget;
  /** UNIQUE per-instance AUTH_SECRET — generated by the reconciler, never logged. */
  authSecret: string;
  /** Cloudflare Access tags shared across the instance pods. */
  cfAccess: { team: string; aud: string };
  /** Optional GitHub OAuth creds for the instance. */
  github?: { clientId: string; clientSecret: string };
  /**
   * Optional OIDC (e.g. Authentik) creds injected so the instance is loginable
   * via the IdP on the LAN. issuer/clientId/name ride in the non-secret env;
   * clientSecret is secret-backed. SECURITY: never log `clientSecret`.
   */
  oidc?: { issuer: string; clientId: string; clientSecret: string; name: string };
  /**
   * Optional image-pull credential for PRIVATE instance images (remote-dev-2xhg).
   * When `name` is set it is referenced in the StatefulSet's `imagePullSecrets`;
   * when `dockerConfigJson` is ALSO set, the provisioner materializes the
   * dockerconfigjson Secret of that name into the instance namespace.
   *
   * SECURITY: `dockerConfigJson` is a SECRET — never log it or the built Secret.
   */
  imagePullSecret?: { name: string; dockerConfigJson?: string };
  /**
   * Optional pod nodeSelector (e.g. `{ "kubernetes.io/arch": "amd64" }`) pinning
   * instance pods to compatible nodes on a mixed-arch cluster (remote-dev-389c).
   */
  nodeSelector?: Record<string, string>;
  // NOTE: first-boot seed emails are intentionally NOT a provisioning input in
  // Phase 1 — the seed Job dispatch is deferred to Phase 2 (jvcx.8). See the
  // comment at the end of provisionInstance.
}

/**
 * Provision an instance transactionally (§6.4). Creates objects in order; on the
 * first failure, deletes the namespace (cascade rollback) and rethrows a
 * {@link ProvisioningError}.
 */
export async function provisionInstance(
  row: InstanceRow,
  opts: ProvisionOptions,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const { slug } = row;
  const namespace = namespaceForSlug(slug);
  const { core, apps } = clients;

  log.info("provisioning instance", {
    slug,
    namespace,
    image: opts.image,
    // Non-secret observability only — NEVER the dockerConfigJson.
    imagePullSecretName: opts.imagePullSecret?.name,
    nodeSelector: opts.nodeSelector,
  });

  try {
    // 1. Namespace.
    await createStep("namespace", () =>
      core.createNamespace({ body: buildNamespace(slug) }),
    );

    // 1b. Image-pull Secret (private instance images, remote-dev-2xhg) — ONLY
    //     when a dockerconfigjson value was provided. When only the NAME is set
    //     (operator pre-provisioned the secret another way) we skip creation but
    //     still reference it in the StatefulSet below.
    if (opts.imagePullSecret?.dockerConfigJson) {
      await createStep("image-pull-secret", () =>
        core.createNamespacedSecret({
          namespace,
          body: buildImagePullSecret(slug, {
            name: opts.imagePullSecret!.name,
            dockerConfigJson: opts.imagePullSecret!.dockerConfigJson!,
          }),
        }),
      );
    }

    // 2. Shared (CF Access) secret.
    await createStep("shared-secret", () =>
      core.createNamespacedSecret({
        namespace,
        body: buildSharedSecret(slug, {
          cfAccessTeam: opts.cfAccess.team,
          cfAccessAud: opts.cfAccess.aud,
        }),
      }),
    );

    // 3. Per-instance auth secret (UNIQUE AUTH_SECRET, optional GitHub).
    await createStep("auth-secret", () =>
      core.createNamespacedSecret({
        namespace,
        body: buildAuthSecret(slug, {
          authSecret: opts.authSecret,
          github: opts.github,
          oidc: opts.oidc ? { clientSecret: opts.oidc.clientSecret } : undefined,
        }),
      }),
    );

    // 4. Governing Service `rdv`.
    await createStep("service", () =>
      core.createNamespacedService({ namespace, body: buildService(slug) }),
    );

    // 5. StatefulSet.
    const env = buildInstanceEnv(slug, {
      host: opts.host,
      oidc: opts.oidc
        ? { issuer: opts.oidc.issuer, clientId: opts.oidc.clientId, name: opts.oidc.name }
        : undefined,
    });
    await createStep("statefulset", () =>
      apps.createNamespacedStatefulSet({
        namespace,
        body: buildStatefulSet(slug, {
          image: opts.image,
          env,
          volumeClaimTemplate: toVolumeClaimTemplate(opts.storage),
          withGithub: Boolean(opts.github),
          withOidc: Boolean(opts.oidc),
          // Referenced whenever the name is set — even without a dockerConfigJson
          // (operator-provisioned pull Secret); the nodeSelector pins arch.
          imagePullSecretName: opts.imagePullSecret?.name,
          nodeSelector: opts.nodeSelector,
        }),
      }),
    );

    // 6. First-boot seed Job — DEFERRED to Phase 2.
    // TODO(jvcx.8): seed must run over HTTP against the ready instance (the RWO
    // PVC can't be co-mounted by a Job while the StatefulSet pod holds it, and
    // `bun run db:seed` talks to the running instance). The builder
    // (buildSeedJob) stays, but provisioning does NOT dispatch it in Phase 1.

    log.info("provisioning succeeded", { slug, namespace });
  } catch (err) {
    // Roll back: delete the namespace (cascade). Best-effort — log if cleanup
    // itself fails, but always rethrow the ORIGINAL provisioning error.
    const stage = err instanceof ProvisioningError ? err.stage : "unknown";
    log.error("provisioning failed; rolling back namespace", {
      slug,
      namespace,
      stage,
      error: String(err),
    });
    try {
      await terminateInstance(slug, clients);
    } catch (rollbackErr) {
      log.error("rollback (namespace delete) failed", {
        slug,
        namespace,
        error: String(rollbackErr),
      });
    }
    throw err;
  }
}

/**
 * Readiness check: StatefulSet `readyReplicas >= 1`.
 *
 * Design (per spec): we gate on `readyReplicas` rather than issuing an in-pod
 * HTTP `GET /<slug>/api/readyz` from the controller. `readyReplicas` is a sound
 * proxy because it ALREADY requires the pod's own readiness probe — which is
 * exactly `GET /<slug>/api/readyz` on 6001 (see buildStatefulSet) — to pass.
 * This avoids the controller needing cluster-DNS reachability to each pod.
 * TODO(jvcx.5+): optionally add a direct HTTP readyz poll via cluster DNS for a
 * second signal once the router/DNS path is exercised end-to-end.
 *
 * A 404 (StatefulSet not yet visible) is reported as not-ready, not an error.
 */
export async function checkInstanceReady(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<{ ready: boolean; reason?: string }> {
  const namespace = namespaceForSlug(slug);
  try {
    const sts = await clients.apps.readNamespacedStatefulSet({
      name: SERVICE_NAME,
      namespace,
    });
    const ready = sts.status?.readyReplicas ?? 0;
    if (ready >= 1) return { ready: true };
    return { ready: false, reason: `readyReplicas=${ready}` };
  } catch (err) {
    if (isNotFound(err)) {
      return { ready: false, reason: "statefulset-not-found" };
    }
    // Transient read error — report not-ready (caller decides on timeout).
    return { ready: false, reason: `read-error: ${String(err)}` };
  }
}

/**
 * Terminate an instance: delete its namespace `rdv-<slug>` (cascade). A 404
 * NotFound means the namespace is already gone — treated as success.
 */
export async function terminateInstance(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const namespace = namespaceForSlug(slug);
  try {
    await clients.core.deleteNamespace({ name: namespace });
    log.info("namespace delete requested", { slug, namespace });
  } catch (err) {
    if (isNotFound(err)) {
      log.debug("namespace already gone (treated as success)", {
        slug,
        namespace,
      });
      return;
    }
    throw err;
  }
}

/**
 * True if the instance's namespace currently exists. A 404 → false; any other
 * error propagates (the caller treats an unknown cluster error as "unknown",
 * not "gone").
 */
export async function namespaceExists(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<boolean> {
  const namespace = namespaceForSlug(slug);
  try {
    await clients.core.readNamespace({ name: namespace });
    return true;
  } catch (err) {
    if (isNotFound(err)) return false;
    throw err;
  }
}

// ── Phase 2 lifecycle helpers (suspend/resume, image rollout, resize, logs,
//    events) — spec §6.3/§6.7/§9. All k8s WRITES here are issued ONLY from the
//    reconciler (the single writer); the read-only helpers (getPodLogs,
//    listInstanceEvents, getStatefulSet, getPvc) are also called live from the
//    API process for the logs/events surfaces. ───────────────────────────────

/**
 * The pod ordinal name a single-replica StatefulSet `rdv` produces: `rdv-0`.
 * Used only as a FALLBACK; {@link getPodLogs} prefers resolving the pod by the
 * `rdv.io/slug` label so a recreated pod (different ordinal is impossible for a
 * 1-replica STS, but a label lookup is more robust) is still found.
 */
const POD_NAME = `${SERVICE_NAME}-0`;

/**
 * The PVC name the StatefulSet's `volumeClaimTemplate` binds for the sole
 * replica: `<volume>-<statefulset>-<ordinal>` == `data-rdv-0`. The template
 * itself is immutable, so a resize patches THIS bound PVC directly (§15 B3).
 */
const PVC_NAME = `${DATA_VOLUME_NAME}-${SERVICE_NAME}-0`;

/** Label selector that matches an instance's pods (set by the StatefulSet). */
function slugSelector(slug: string): string {
  return `rdv.io/slug=${slug}`;
}

/** Read-only StatefulSet snapshot the reconciler converges against. */
export interface StatefulSetState {
  /** False when the StatefulSet (or namespace) is not present yet (404). */
  found: boolean;
  /** Desired replicas per `.spec.replicas` (defaults to 0 when unset). */
  replicas: number;
  /** Currently-ready replicas per `.status.readyReplicas`. */
  readyReplicas: number;
  /** The container[0] image currently running, or undefined when unknown. */
  image?: string;
}

/**
 * Read the instance's StatefulSet. A 404 (namespace/STS not yet visible) is
 * reported as `{ found: false }` — NOT an error — so the reconciler can treat a
 * missing STS as "nothing to converge" without tearing anything down.
 */
export async function getStatefulSet(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<StatefulSetState> {
  const namespace = namespaceForSlug(slug);
  try {
    const sts = await clients.apps.readNamespacedStatefulSet({
      name: SERVICE_NAME,
      namespace,
    });
    return {
      found: true,
      replicas: sts.spec?.replicas ?? 0,
      readyReplicas: sts.status?.readyReplicas ?? 0,
      image: sts.spec?.template?.spec?.containers?.[0]?.image,
    };
  } catch (err) {
    if (isNotFound(err)) return { found: false, replicas: 0, readyReplicas: 0 };
    throw err;
  }
}

/**
 * Scale the StatefulSet to `replicas` via the scale subresource.
 *
 * The body MUST be a JSON Patch array (`[{op,path,value}]`): the installed
 * `@kubernetes/client-node@1.4.0` object-param API negotiates the patch
 * Content-Type to the FIRST entry of its accept list
 * (`application/json-patch+json`), so a merge object would be sent as
 * json-patch and rejected. `/spec/replicas` always exists on a Scale, so
 * `replace` is correct and content-type-safe.
 */
export async function setStatefulSetReplicas(
  slug: string,
  replicas: number,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const namespace = namespaceForSlug(slug);
  await clients.apps.patchNamespacedStatefulSetScale({
    name: SERVICE_NAME,
    namespace,
    body: [{ op: "replace", path: "/spec/replicas", value: replicas }],
  });
  log.info("statefulset scale patched", { slug, namespace, replicas });
}

/**
 * Roll the StatefulSet's container[0] image to `image` (rolling update, §9).
 * JSON Patch array for the same content-type reason as
 * {@link setStatefulSetReplicas}; `/spec/template/spec/containers/0/image`
 * always exists.
 */
export async function setStatefulSetImage(
  slug: string,
  image: string,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const namespace = namespaceForSlug(slug);
  await clients.apps.patchNamespacedStatefulSet({
    name: SERVICE_NAME,
    namespace,
    body: [
      {
        op: "replace",
        path: "/spec/template/spec/containers/0/image",
        value: image,
      },
    ],
  });
  log.info("statefulset image patched", { slug, namespace, image });
}

/** A PVC capacity snapshot (the bound `data-rdv-0`). */
export interface PvcState {
  /** False when the PVC is not present yet (404). */
  found: boolean;
  /** `.spec.resources.requests.storage` (the requested size). */
  requestedStorage?: string;
  /** `.status.capacity.storage` (the actually-provisioned size). */
  capacityStorage?: string;
}

/**
 * Read the instance's bound data PVC (`data-rdv-0`). A 404 → `{ found: false }`.
 */
export async function getPvc(
  slug: string,
  clients: K8sClients = defaultClients(),
): Promise<PvcState> {
  const namespace = namespaceForSlug(slug);
  try {
    const pvc = await clients.core.readNamespacedPersistentVolumeClaim({
      name: PVC_NAME,
      namespace,
    });
    return {
      found: true,
      requestedStorage: pvc.spec?.resources?.requests?.storage,
      capacityStorage: pvc.status?.capacity?.storage,
    };
  } catch (err) {
    if (isNotFound(err)) return { found: false };
    throw err;
  }
}

/**
 * Resize (grow-only) the bound data PVC to `size`. JSON Patch array (same
 * content-type reason as above); `/spec/resources/requests/storage` always
 * exists. k8s forbids shrinking and a StorageClass without
 * `allowVolumeExpansion` rejects the patch — callers (the reconciler) catch
 * such rejections and audit `resize:failed` WITHOUT failing the instance.
 */
export async function resizePvc(
  slug: string,
  size: string,
  clients: K8sClients = defaultClients(),
): Promise<void> {
  const namespace = namespaceForSlug(slug);
  await clients.core.patchNamespacedPersistentVolumeClaim({
    name: PVC_NAME,
    namespace,
    body: [
      { op: "replace", path: "/spec/resources/requests/storage", value: size },
    ],
  });
  log.info("pvc resize patched", { slug, namespace, size });
}

/** Pod logs (tail) for the instance's sole pod. */
export interface PodLogsResult {
  /** The resolved pod name, or null when no pod is running. */
  pod: string | null;
  /** The tail of the container log (empty string when no pod). */
  logs: string;
}

/**
 * Tail the instance pod's `rdv` container log. Resolves the pod by the
 * `rdv.io/slug` label (robust); falls back to the conventional `rdv-0` name
 * when the list returns nothing but a pod may still exist. No pod at all (e.g.
 * a suspended instance scaled to 0) → `{ pod: null, logs: "" }`.
 */
export async function getPodLogs(
  slug: string,
  opts: { tailLines?: number; previous?: boolean },
  clients: K8sClients = defaultClients(),
): Promise<PodLogsResult> {
  const namespace = namespaceForSlug(slug);
  // Prefer resolving the pod by label (robust); fall back to the conventional
  // `rdv-0` ordinal name when the list returns nothing (e.g. a stale label
  // cache) OR the list call itself fails transiently, so a running pod is still
  // found. The subsequent log read is guarded (404 → no pod).
  let podName = POD_NAME;
  try {
    const pods = await clients.core.listNamespacedPod({
      namespace,
      labelSelector: slugSelector(slug),
    });
    podName = pods.items[0]?.metadata?.name ?? POD_NAME;
  } catch (err) {
    log.debug("listNamespacedPod failed; falling back to conventional pod name", {
      slug,
      pod: POD_NAME,
      error: String(err),
    });
  }

  try {
    const logs = await clients.core.readNamespacedPodLog({
      name: podName,
      namespace,
      container: SERVICE_NAME,
      tailLines: opts.tailLines,
      previous: opts.previous,
      timestamps: true,
    });
    return { pod: podName, logs: logs ?? "" };
  } catch (err) {
    // No pod running (suspended / between rollouts) → degrade gracefully.
    if (isNotFound(err)) return { pod: null, logs: "" };
    throw err;
  }
}

/** A small, UI-facing projection of a k8s Event. */
export interface InstanceEventDTO {
  type: string;
  reason: string;
  message: string;
  count: number;
  /** The most recent occurrence time as an ISO string, or null. */
  lastSeen: string | null;
  /** `Kind/name` of the object the event is about (e.g. `Pod/rdv-0`). */
  involvedObject: string;
}

/**
 * List the instance namespace's events, newest first, mapped to a small DTO.
 * Used by the read-only events surface (`GET /api/instances/:id/events`).
 */
export async function listInstanceEvents(
  slug: string,
  clients: K8sClients = defaultClients(),
  limit = 100,
): Promise<InstanceEventDTO[]> {
  const namespace = namespaceForSlug(slug);
  const list = await clients.core.listNamespacedEvent({ namespace, limit });
  const events = list.items.map((e): InstanceEventDTO => {
    const last = e.lastTimestamp ?? e.eventTime ?? e.firstTimestamp ?? null;
    const obj = e.involvedObject;
    const involvedObject =
      obj?.kind && obj?.name ? `${obj.kind}/${obj.name}` : (obj?.name ?? "");
    return {
      type: e.type ?? "Normal",
      reason: e.reason ?? "",
      message: e.message ?? "",
      count: e.count ?? 1,
      lastSeen: last ? new Date(last).toISOString() : null,
      involvedObject,
    };
  });
  // Newest first (descending by lastSeen; nulls sort last).
  events.sort((a, b) => (b.lastSeen ?? "").localeCompare(a.lastSeen ?? ""));
  return events;
}

/**
 * Parse a k8s storage quantity (`Ki`/`Mi`/`Gi`/`Ti` binary suffixes, or a plain
 * byte count) to an integer number of bytes. Returns null for an unparseable /
 * non-positive / non-finite value so callers can reject it (HTTP 400) rather
 * than mis-compare. A PVC request of zero is meaningless, so `"0"`/`"0Gi"` are
 * rejected too.
 *
 * Scope: only the binary IEC suffixes a PVC request realistically uses. Decimal
 * SI suffixes (K/M/G/T) and milli-quantities are intentionally NOT accepted —
 * the create form + resize UI only ever emit `<n>Gi`.
 */
const QUANTITY_PATTERN = /^(\d+(?:\.\d+)?)(Ki|Mi|Gi|Ti)?$/;
const QUANTITY_MULTIPLIERS: Record<string, number> = {
  Ki: 1024,
  Mi: 1024 ** 2,
  Gi: 1024 ** 3,
  Ti: 1024 ** 4,
};

export function parseQuantityToBytes(value: string | null | undefined): number | null {
  if (typeof value !== "string") return null;
  const match = QUANTITY_PATTERN.exec(value.trim());
  if (!match) return null;
  const amount = Number(match[1]);
  if (!Number.isFinite(amount) || amount <= 0) return null;
  const multiplier = match[2] ? QUANTITY_MULTIPLIERS[match[2]] : 1;
  return Math.round(amount * multiplier);
}
