// AUTO-GENERATED by scripts/codegen-schema.ts — DO NOT EDIT.
// Edit schema.def.ts and run `bun run db:codegen`.

import { sqliteTable, text, integer, index, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";
import type { AdapterAccountType } from "next-auth/adapters";
import type { SessionStatus } from "@/types/session";
import type { CIStatusState, PRState } from "@/types/github-stats";
import type { ScheduleType, ScheduleStatus, ExecutionStatus } from "@/types/schedule";
import type { AgentProvider, AgentConfigType, MCPTransport } from "@/types/agent";
import type { AgentProviderType, WorktreeType } from "@/types/session";
import type { TerminalType, AgentExitState } from "@/types/terminal-type";
import type { AppearanceMode, ColorSchemeCategory, ColorSchemeId } from "@/types/appearance";
import type { TaskPriority, TaskStatus, TaskSource } from "@/types/task";
import type { NotificationType, NotificationSeverity, NotificationMeta } from "@/types/notification";
import type { ChannelType } from "@/types/channels";
import type { AgentRunStatus, AgentRunSource, TriggerKind } from "@/types/agent-run";
import type { CrownRunStatus } from "@/types/crown";
import type { MigrationJobStatus, MigrationImportStatus, MigrationWorkingTreeMode } from "@/types/migration";
import type { ClaudeAccountKind, ClaudeLimitStatus, UsageDetectionSource, ClaudeAutoRelaunchMode } from "@/types/claude-limits";

export const users = sqliteTable(
  "user",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name"),
    email: text("email").unique(),
    emailVerified: integer("emailVerified", { mode: "timestamp_ms" }),
    image: text("image"),
  }
);

export const userEmails = sqliteTable(
  "user_email",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    email: text("email").notNull().unique(),
    isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("user_email_email_unique").on(table.email),
    index("user_email_user_idx").on(table.userId),
  ]
);

export const accounts = sqliteTable(
  "account",
  {
    userId: text("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (table) => [
    primaryKey({ columns: [table.provider, table.providerAccountId] }),
    index("account_user_idx").on(table.userId),
  ]
);

export const sessions = sqliteTable(
  "session",
  {
    sessionToken: text("sessionToken").primaryKey(),
    userId: text("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
    expires: integer("expires", { mode: "timestamp_ms" }).notNull(),
  }
);

export const verificationTokens = sqliteTable(
  "verificationToken",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: integer("expires", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.identifier, table.token] }),
  ]
);

export const authorizedUsers = sqliteTable(
  "authorized_user",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    email: text("email").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const userSettings = sqliteTable(
  "user_settings",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }),
    defaultWorkingDirectory: text("default_working_directory"),
    defaultShell: text("default_shell"),
    startupCommand: text("startup_command"),
    xtermScrollback: integer("xterm_scrollback").default(10000),
    tmuxHistoryLimit: integer("tmux_history_limit").default(50000),
    theme: text("theme").default("tokyo-night"),
    fontSize: integer("font_size").default(14),
    fontFamily: text("font_family").default("'JetBrainsMono Nerd Font Mono', monospace"),
    activeNodeId: text("active_node_id"),
    activeNodeType: text("active_node_type", { enum: ["group","project"] }),
    pinnedNodeId: text("pinned_node_id"),
    pinnedNodeType: text("pinned_node_type", { enum: ["group","project"] }),
    autoFollowActiveSession: integer("auto_follow_active_session", { mode: "boolean" }).notNull().default(true),
    notificationsEnabled: integer("notifications_enabled", { mode: "boolean" }).notNull().default(true),
    defaultAgentProvider: text("default_agent_provider"),
    agentProviderSettings: text("agent_provider_settings", { mode: "json" }),
    beadsSidebarCollapsed: integer("beads_sidebar_collapsed", { mode: "boolean" }).notNull().default(true),
    beadsSidebarWidth: integer("beads_sidebar_width").default(320),
    beadsClosedRetentionDays: integer("beads_closed_retention_days").default(7),
    beadsSectionExpanded: text("beads_section_expanded"),
    claudeAutoRelaunchMode: text("claude_auto_relaunch_mode").$type<ClaudeAutoRelaunchMode>().notNull().default("notify"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const githubRepositories = sqliteTable(
  "github_repository",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    githubId: integer("github_id").notNull(),
    name: text("name").notNull(),
    fullName: text("full_name").notNull(),
    cloneUrl: text("clone_url").notNull(),
    defaultBranch: text("default_branch").notNull(),
    localPath: text("local_path"),
    isPrivate: integer("is_private", { mode: "boolean" }).notNull().default(false),
    addedAt: integer("added_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("github_repo_user_idx").on(table.userId),
    index("github_repo_github_id_idx").on(table.userId, table.githubId),
  ]
);

export const githubAccountMetadata = sqliteTable(
  "github_account_metadata",
  {
    providerAccountId: text("provider_account_id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    login: text("login").notNull(),
    displayName: text("display_name"),
    avatarUrl: text("avatar_url").notNull(),
    email: text("email"),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    configDir: text("config_dir").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("github_account_metadata_user_idx").on(table.userId),
  ]
);

export const portRegistry = sqliteTable(
  "port_registry",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    port: integer("port").notNull(),
    variableName: text("variable_name").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("port_registry_user_idx").on(table.userId),
    index("port_registry_project_idx").on(table.projectId),
    index("port_registry_user_port_idx").on(table.userId, table.port),
    uniqueIndex("port_registry_user_port_var_unique").on(table.userId, table.port, table.variableName),
  ]
);

export const portClaims = sqliteTable(
  "port_claim",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    sessionId: text("session_id").notNull().references(() => terminalSessions.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }),
    port: integer("port").notNull(),
    variableName: text("variable_name").notNull(),
    isListening: integer("is_listening", { mode: "boolean" }),
    pid: integer("pid"),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    claimedAt: integer("claimed_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("port_claim_session_idx").on(table.sessionId),
    index("port_claim_user_idx").on(table.userId),
    index("port_claim_port_idx").on(table.port),
    uniqueIndex("port_claim_session_port_unique").on(table.sessionId, table.port),
  ]
);

export const sessionTemplates = sqliteTable(
  "session_template",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    sessionNamePattern: text("session_name_pattern"),
    projectPath: text("project_path"),
    startupCommand: text("startup_command"),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    icon: text("icon"),
    theme: text("theme"),
    fontSize: integer("font_size"),
    fontFamily: text("font_family"),
    usageCount: integer("usage_count").notNull().default(0),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("session_template_user_idx").on(table.userId),
    index("session_template_usage_idx").on(table.userId, table.usageCount),
    index("session_template_project_idx").on(table.projectId),
  ]
);

export const sessionRecordings = sqliteTable(
  "session_recording",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id"),
    name: text("name").notNull(),
    description: text("description"),
    duration: integer("duration").notNull(),
    terminalCols: integer("terminal_cols").notNull().default(80),
    terminalRows: integer("terminal_rows").notNull().default(24),
    data: text("data").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("session_recording_user_idx").on(table.userId),
    index("session_recording_created_idx").on(table.userId, table.createdAt),
  ]
);

export const apiKeys = sqliteTable(
  "api_key",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    keyPrefix: text("key_prefix").notNull(),
    keyHash: text("key_hash").notNull(),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("api_key_user_idx").on(table.userId),
    index("api_key_prefix_idx").on(table.keyPrefix),
  ]
);

export const modelProxyTokens = sqliteTable(
  "model_proxy_token",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => terminalSessions.id, { onDelete: "cascade" }),
    instanceSlug: text("instance_slug"),
    tokenPrefix: text("token_prefix").notNull(),
    tokenHash: text("token_hash").notNull(),
    providerScope: text("provider_scope").notNull().default("[\"anthropic\"]"),
    revokedAt: integer("revoked_at", { mode: "timestamp_ms" }),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("model_proxy_token_prefix_idx").on(table.tokenPrefix),
    index("model_proxy_token_session_idx").on(table.sessionId),
    index("model_proxy_token_user_idx").on(table.userId),
  ]
);

export const modelUsageEvents = sqliteTable(
  "model_usage_event",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull(),
    sessionId: text("session_id"),
    instanceSlug: text("instance_slug"),
    provider: text("provider").notNull(),
    model: text("model"),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    cacheReadTokens: integer("cache_read_tokens").notNull().default(0),
    cacheCreationTokens: integer("cache_creation_tokens").notNull().default(0),
    costMicroUsd: integer("cost_micro_usd"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("model_usage_session_idx").on(table.sessionId),
    index("model_usage_user_idx").on(table.userId),
    index("model_usage_instance_idx").on(table.instanceSlug),
    index("model_usage_created_idx").on(table.createdAt),
  ]
);

export const terminalSessions = sqliteTable(
  "terminal_session",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    tmuxSessionName: text("tmux_session_name").notNull().unique(),
    projectPath: text("project_path"),
    githubRepoId: text("github_repo_id").references(() => githubRepositories.id, { onDelete: "set null" }),
    worktreeBranch: text("worktree_branch"),
    worktreeType: text("worktree_type").$type<WorktreeType>(),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    profileId: text("profile_id").references(() => agentProfiles.id, { onDelete: "set null" }),
    terminalType: text("terminal_type").$type<TerminalType>().default("shell"),
    agentProvider: text("agent_provider").$type<AgentProviderType>(),
    agentExitState: text("agent_exit_state").$type<AgentExitState>(),
    agentExitCode: integer("agent_exit_code"),
    agentExitedAt: integer("agent_exited_at", { mode: "timestamp_ms" }),
    agentRestartCount: integer("agent_restart_count").default(0),
    agentActivityStatus: text("agent_activity_status"),
    agentActivityStatusAt: integer("agent_activity_status_at"),
    typeMetadata: text("type_metadata"),
    scopeKey: text("scope_key"),
    parentSessionId: text("parent_session_id"),
    orchestratorRole: text("orchestrator_role").$type<"parent" | "child">(),
    status: text("status").$type<SessionStatus>().notNull().default("active"),
    pinned: integer("pinned", { mode: "boolean" }).notNull().default(false),
    tabOrder: integer("tab_order").notNull().default(0),
    lastActivityAt: integer("last_activity_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("terminal_session_user_status_idx").on(table.userId, table.status),
    index("terminal_session_user_order_idx").on(table.userId, table.tabOrder),
    index("terminal_session_project_idx").on(table.projectId),
    index("terminal_session_type_idx").on(table.userId, table.terminalType),
    uniqueIndex("terminal_session_scope_unique_idx").on(table.userId, table.terminalType, table.scopeKey),
  ]
);

export const trashItems = sqliteTable(
  "trash_item",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    resourceType: text("resource_type").notNull(),
    resourceId: text("resource_id").notNull(),
    resourceName: text("resource_name").notNull(),
    trashedAt: integer("trashed_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)),
  },
  (table) => [
    index("trash_item_user_type_idx").on(table.userId, table.resourceType),
    index("trash_item_expires_idx").on(table.expiresAt),
    index("trash_item_resource_idx").on(table.resourceType, table.resourceId),
  ]
);

export const worktreeTrashMetadata = sqliteTable(
  "worktree_trash_metadata",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    trashItemId: text("trash_item_id").notNull().unique().references(() => trashItems.id, { onDelete: "cascade" }),
    githubRepoId: text("github_repo_id").references(() => githubRepositories.id, { onDelete: "set null" }),
    repoName: text("repo_name").notNull(),
    repoLocalPath: text("repo_local_path").notNull(),
    worktreeBranch: text("worktree_branch").notNull(),
    worktreeOriginalPath: text("worktree_original_path").notNull(),
    worktreeTrashPath: text("worktree_trash_path").notNull(),
    originalProjectId: text("original_project_id"),
    originalProjectName: text("original_project_name"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("worktree_trash_repo_idx").on(table.githubRepoId),
  ]
);

export const githubRepositoryStats = sqliteTable(
  "github_repository_stats",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    repositoryId: text("repository_id").notNull().unique().references(() => githubRepositories.id, { onDelete: "cascade" }),
    openPRCount: integer("open_pr_count").notNull().default(0),
    openIssueCount: integer("open_issue_count").notNull().default(0),
    ciStatus: text("ci_status").$type<CIStatusState>(),
    ciStatusDetails: text("ci_status_details"),
    branchProtected: integer("branch_protected", { mode: "boolean" }).notNull().default(false),
    branchProtectionDetails: text("branch_protection_details"),
    recentCommits: text("recent_commits"),
    cachedAt: integer("cached_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date(Date.now() + 15 * 60 * 1000)),
  },
  (table) => [
    index("github_repo_stats_repo_idx").on(table.repositoryId),
    index("github_repo_stats_expires_idx").on(table.expiresAt),
  ]
);

export const githubPullRequests = sqliteTable(
  "github_pull_request",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    repositoryId: text("repository_id").notNull().references(() => githubRepositories.id, { onDelete: "cascade" }),
    prNumber: integer("pr_number").notNull(),
    title: text("title").notNull(),
    state: text("state").$type<PRState>().notNull(),
    branch: text("branch").notNull(),
    baseBranch: text("base_branch").notNull(),
    author: text("author").notNull(),
    authorAvatarUrl: text("author_avatar_url"),
    url: text("url").notNull(),
    isDraft: integer("is_draft", { mode: "boolean" }).notNull().default(false),
    additions: integer("additions").notNull().default(0),
    deletions: integer("deletions").notNull().default(0),
    reviewDecision: text("review_decision").$type<"APPROVED" | "CHANGES_REQUESTED" | "REVIEW_REQUIRED">(),
    ciStatus: text("ci_status").$type<CIStatusState>(),
    isNew: integer("is_new", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
    cachedAt: integer("cached_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("github_pr_repo_idx").on(table.repositoryId),
    index("github_pr_repo_number_idx").on(table.repositoryId, table.prNumber),
    index("github_pr_state_idx").on(table.repositoryId, table.state),
  ]
);

export const githubBranchProtection = sqliteTable(
  "github_branch_protection",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    repositoryId: text("repository_id").notNull().references(() => githubRepositories.id, { onDelete: "cascade" }),
    branch: text("branch").notNull(),
    isProtected: integer("is_protected", { mode: "boolean" }).notNull().default(false),
    requiresReview: integer("requires_review", { mode: "boolean" }).notNull().default(false),
    requiredReviewers: integer("required_reviewers").notNull().default(0),
    requiresStatusChecks: integer("requires_status_checks", { mode: "boolean" }).notNull().default(false),
    requiredChecks: text("required_checks"),
    allowsForcePushes: integer("allows_force_pushes", { mode: "boolean" }).notNull().default(false),
    allowsDeletions: integer("allows_deletions", { mode: "boolean" }).notNull().default(false),
    cachedAt: integer("cached_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("github_branch_protection_repo_branch_idx").on(table.repositoryId, table.branch),
  ]
);

export const githubStatsPreferences = sqliteTable(
  "github_stats_preferences",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }),
    showPRCount: integer("show_pr_count", { mode: "boolean" }).notNull().default(true),
    showIssueCount: integer("show_issue_count", { mode: "boolean" }).notNull().default(true),
    showCIStatus: integer("show_ci_status", { mode: "boolean" }).notNull().default(true),
    showRecentCommits: integer("show_recent_commits", { mode: "boolean" }).notNull().default(true),
    showBranchProtection: integer("show_branch_protection", { mode: "boolean" }).notNull().default(true),
    refreshIntervalMinutes: integer("refresh_interval_minutes").notNull().default(15),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("github_stats_prefs_user_idx").on(table.userId),
    index("github_stats_prefs_project_idx").on(table.projectId),
  ]
);

export const githubChangeNotifications = sqliteTable(
  "github_change_notification",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    repositoryId: text("repository_id").notNull().references(() => githubRepositories.id, { onDelete: "cascade" }),
    newPRCount: integer("new_pr_count").notNull().default(0),
    newIssueCount: integer("new_issue_count").notNull().default(0),
    lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("github_notifications_user_repo_idx").on(table.userId, table.repositoryId),
    index("github_notifications_user_idx").on(table.userId),
  ]
);

export const githubIssues = sqliteTable(
  "github_issue",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    repositoryId: text("repository_id").notNull().references(() => githubRepositories.id, { onDelete: "cascade" }),
    issueNumber: integer("issue_number").notNull(),
    title: text("title").notNull(),
    state: text("state").$type<"open" | "closed">().notNull(),
    body: text("body"),
    htmlUrl: text("html_url").notNull(),
    author: text("author"),
    labels: text("labels").notNull().default("[]"),
    assignees: text("assignees").notNull().default("[]"),
    milestone: text("milestone"),
    comments: integer("comments").notNull().default(0),
    isPullRequest: integer("is_pull_request", { mode: "boolean" }).notNull().default(false),
    isNew: integer("is_new", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
    cachedAt: integer("cached_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("github_issue_repo_idx").on(table.repositoryId),
    uniqueIndex("github_issue_repo_number_idx").on(table.repositoryId, table.issueNumber),
    index("github_issue_state_idx").on(table.repositoryId, table.state),
    index("github_issue_cached_idx").on(table.cachedAt),
  ]
);

export const sessionSchedules = sqliteTable(
  "session_schedule",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id").notNull().references(() => terminalSessions.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    scheduleType: text("schedule_type").$type<ScheduleType>().notNull().default("one-time"),
    cronExpression: text("cron_expression"),
    scheduledAt: integer("scheduled_at", { mode: "timestamp_ms" }),
    timezone: text("timezone").notNull().default("America/Los_Angeles"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    status: text("status").$type<ScheduleStatus>().notNull().default("active"),
    maxRetries: integer("max_retries").notNull().default(0),
    retryDelaySeconds: integer("retry_delay_seconds").notNull().default(60),
    timeoutSeconds: integer("timeout_seconds").notNull().default(300),
    lastRunAt: integer("last_run_at", { mode: "timestamp_ms" }),
    lastRunStatus: text("last_run_status").$type<ExecutionStatus>(),
    nextRunAt: integer("next_run_at", { mode: "timestamp_ms" }),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("session_schedule_user_idx").on(table.userId),
    index("session_schedule_session_idx").on(table.sessionId),
    index("session_schedule_next_run_idx").on(table.enabled, table.nextRunAt),
  ]
);

export const scheduleCommands = sqliteTable(
  "schedule_command",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    scheduleId: text("schedule_id").notNull().references(() => sessionSchedules.id, { onDelete: "cascade" }),
    command: text("command").notNull(),
    order: integer("order").notNull(),
    delayBeforeSeconds: integer("delay_before_seconds").notNull().default(0),
    continueOnError: integer("continue_on_error", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("schedule_command_schedule_idx").on(table.scheduleId),
    index("schedule_command_order_idx").on(table.scheduleId, table.order),
  ]
);

export const scheduleExecutions = sqliteTable(
  "schedule_execution",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    scheduleId: text("schedule_id").notNull().references(() => sessionSchedules.id, { onDelete: "cascade" }),
    status: text("status").$type<ExecutionStatus>().notNull(),
    startedAt: integer("started_at", { mode: "timestamp_ms" }).notNull(),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }).notNull(),
    durationMs: integer("duration_ms").notNull(),
    commandCount: integer("command_count").notNull(),
    successCount: integer("success_count").notNull(),
    failureCount: integer("failure_count").notNull(),
    errorMessage: text("error_message"),
    output: text("output"),
  },
  (table) => [
    index("schedule_execution_schedule_idx").on(table.scheduleId),
    index("schedule_execution_started_idx").on(table.scheduleId, table.startedAt),
  ]
);

export const commandExecutions = sqliteTable(
  "command_execution",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    executionId: text("execution_id").notNull().references(() => scheduleExecutions.id, { onDelete: "cascade" }),
    commandId: text("command_id").notNull().references(() => scheduleCommands.id, { onDelete: "cascade" }),
    command: text("command").notNull(),
    status: text("status").$type<ExecutionStatus>().notNull(),
    exitCode: integer("exit_code"),
    startedAt: integer("started_at", { mode: "timestamp_ms" }).notNull(),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }).notNull(),
    durationMs: integer("duration_ms").notNull(),
    output: text("output"),
    errorMessage: text("error_message"),
  },
  (table) => [
    index("command_execution_execution_idx").on(table.executionId),
    index("command_execution_command_idx").on(table.commandId),
  ]
);

export const setupConfig = sqliteTable(
  "setup_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    workingDirectory: text("working_directory").notNull(),
    nextPort: integer("next_port").notNull().default(3000),
    terminalPort: integer("terminal_port").notNull().default(3001),
    wslDistribution: text("wsl_distribution"),
    autoStart: integer("auto_start", { mode: "boolean" }).notNull().default(true),
    checkForUpdates: integer("check_for_updates", { mode: "boolean" }).notNull().default(true),
    isComplete: integer("is_complete", { mode: "boolean" }).notNull().default(false),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const agentProfiles = sqliteTable(
  "agent_profile",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    provider: text("provider").$type<AgentProvider>().notNull().default("all"),
    configDir: text("config_dir").notNull(),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_profile_user_idx").on(table.userId),
    index("agent_profile_default_idx").on(table.userId, table.isDefault),
  ]
);

export const agentConfigs = sqliteTable(
  "agent_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }),
    provider: text("provider").$type<AgentProvider>().notNull(),
    configType: text("config_type").$type<AgentConfigType>().notNull(),
    content: text("content").notNull().default(""),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_config_user_idx").on(table.userId),
    index("agent_config_project_idx").on(table.projectId),
    uniqueIndex("agent_config_unique_idx").on(table.userId, table.projectId, table.provider, table.configType),
  ]
);

export const mcpServers = sqliteTable(
  "mcp_server",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    transport: text("transport").$type<MCPTransport>().notNull().default("stdio"),
    command: text("command").notNull(),
    args: text("args").notNull().default("[]"),
    env: text("env").notNull().default("{}"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    autoStart: integer("auto_start", { mode: "boolean" }).notNull().default(false),
    lastHealthCheck: integer("last_health_check", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("mcp_server_user_idx").on(table.userId),
    index("mcp_server_project_idx").on(table.projectId),
    index("mcp_server_enabled_idx").on(table.userId, table.enabled),
  ]
);

export const profileGitIdentities = sqliteTable(
  "profile_git_identity",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    profileId: text("profile_id").notNull().unique().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userName: text("user_name").notNull(),
    userEmail: text("user_email").notNull(),
    sshKeyPath: text("ssh_key_path"),
    gpgKeyId: text("gpg_key_id"),
    githubUsername: text("github_username"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("profile_git_identity_profile_idx").on(table.profileId),
  ]
);

export const profileSecretsConfig = sqliteTable(
  "profile_secrets_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    profileId: text("profile_id").notNull().unique().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    providerConfig: text("provider_config").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    lastFetchedAt: integer("last_fetched_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("profile_secrets_config_profile_idx").on(table.profileId),
    index("profile_secrets_config_user_idx").on(table.userId),
  ]
);

export const mcpDiscoveredTools = sqliteTable(
  "mcp_discovered_tool",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    serverId: text("server_id").notNull().references(() => mcpServers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    inputSchema: text("input_schema"),
    discoveredAt: integer("discovered_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("mcp_discovered_tool_server_idx").on(table.serverId),
    uniqueIndex("mcp_discovered_tool_unique_idx").on(table.serverId, table.name),
  ]
);

export const mcpDiscoveredResources = sqliteTable(
  "mcp_discovered_resource",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    serverId: text("server_id").notNull().references(() => mcpServers.id, { onDelete: "cascade" }),
    uri: text("uri").notNull(),
    name: text("name"),
    description: text("description"),
    mimeType: text("mime_type"),
    discoveredAt: integer("discovered_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("mcp_discovered_resource_server_idx").on(table.serverId),
    uniqueIndex("mcp_discovered_resource_unique_idx").on(table.serverId, table.uri),
  ]
);

export const agentActivityEvents = sqliteTable(
  "agent_activity_event",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    agentProvider: text("agent_provider").$type<AgentProviderType>(),
    eventType: text("event_type").notNull(),
    eventData: text("event_data"),
    duration: integer("duration"),
    success: integer("success", { mode: "boolean" }),
    errorMessage: text("error_message"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_activity_user_idx").on(table.userId),
    index("agent_activity_session_idx").on(table.sessionId),
    index("agent_activity_provider_idx").on(table.userId, table.agentProvider),
    index("agent_activity_event_type_idx").on(table.userId, table.eventType),
    index("agent_activity_created_idx").on(table.userId, table.createdAt),
  ]
);

export const agentDailyStats = sqliteTable(
  "agent_daily_stats",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    date: text("date").notNull(),
    agentProvider: text("agent_provider").$type<AgentProviderType>(),
    sessionCount: integer("session_count").notNull().default(0),
    commandCount: integer("command_count").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    totalDuration: integer("total_duration").notNull().default(0),
    toolCallCount: integer("tool_call_count").notNull().default(0),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("agent_daily_stats_unique_idx").on(table.userId, table.date, table.agentProvider),
    index("agent_daily_stats_user_date_idx").on(table.userId, table.date),
  ]
);

export const sessionMemory = sqliteTable(
  "session_memory",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    type: text("type").$type<"note" | "artifact" | "summary">().notNull(),
    title: text("title").notNull(),
    content: text("content").notNull(),
    tags: text("tags").notNull().default("[]"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("session_memory_user_idx").on(table.userId),
    index("session_memory_project_idx").on(table.projectId),
    index("session_memory_type_idx").on(table.userId, table.type),
  ]
);

export const colorSchemes = sqliteTable(
  "color_scheme",
  {
    id: text("id").primaryKey().$type<ColorSchemeId>(),
    name: text("name").notNull(),
    description: text("description"),
    category: text("category").$type<ColorSchemeCategory>().notNull(),
    colorDefinitions: text("color_definitions").notNull(),
    terminalPalette: text("terminal_palette"),
    isBuiltIn: integer("is_built_in", { mode: "boolean" }).notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("color_scheme_category_idx").on(table.category),
    index("color_scheme_sort_idx").on(table.sortOrder),
  ]
);

export const appearanceSettings = sqliteTable(
  "appearance_settings",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }),
    appearanceMode: text("appearance_mode").$type<AppearanceMode>().notNull().default("system"),
    lightColorScheme: text("light_color_scheme").$type<ColorSchemeId>().notNull().default("ocean"),
    darkColorScheme: text("dark_color_scheme").$type<ColorSchemeId>().notNull().default("midnight"),
    terminalOpacity: integer("terminal_opacity").notNull().default(100),
    terminalBlur: integer("terminal_blur").notNull().default(0),
    terminalCursorStyle: text("terminal_cursor_style").$type<"block" | "underline" | "bar">().notNull().default("block"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("appearance_settings_user_idx").on(table.userId),
  ]
);

export const agentProfileJsonConfigs = sqliteTable(
  "agent_profile_json_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    profileId: text("profile_id").notNull().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    agentType: text("agent_type").$type<Exclude<AgentProvider, "all">>().notNull(),
    configJson: text("config_json").notNull().default("{}"),
    isValid: integer("is_valid", { mode: "boolean" }).notNull().default(true),
    validationErrors: text("validation_errors"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_profile_json_config_profile_idx").on(table.profileId),
    index("agent_profile_json_config_user_idx").on(table.userId),
    uniqueIndex("agent_profile_json_config_unique_idx").on(table.profileId, table.agentType),
  ]
);

export const profileAppearanceSettings = sqliteTable(
  "profile_appearance_settings",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    profileId: text("profile_id").notNull().unique().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    appearanceMode: text("appearance_mode").$type<AppearanceMode>().notNull().default("system"),
    lightColorScheme: text("light_color_scheme").$type<ColorSchemeId>().notNull().default("ocean"),
    darkColorScheme: text("dark_color_scheme").$type<ColorSchemeId>().notNull().default("midnight"),
    terminalOpacity: integer("terminal_opacity").notNull().default(100),
    terminalBlur: integer("terminal_blur").notNull().default(0),
    terminalCursorStyle: text("terminal_cursor_style").$type<"block" | "underline" | "bar">().notNull().default("block"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("profile_appearance_profile_idx").on(table.profileId),
    index("profile_appearance_user_idx").on(table.userId),
  ]
);

export const projectTasks = sqliteTable(
  "project_task",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status").$type<TaskStatus>().notNull().default("open"),
    priority: text("priority").$type<TaskPriority>().notNull().default("medium"),
    source: text("source").$type<TaskSource>().notNull().default("manual"),
    labels: text("labels").notNull().default("[]"),
    subtasks: text("subtasks").notNull().default("[]"),
    metadata: text("metadata").notNull().default("{}"),
    instructions: text("instructions"),
    agentTaskKey: text("agent_task_key"),
    owner: text("owner"),
    dueDate: integer("due_date", { mode: "timestamp_ms" }),
    githubIssueUrl: text("github_issue_url"),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("project_task_user_idx").on(table.userId),
    index("project_task_project_idx").on(table.projectId),
    index("project_task_user_project_idx").on(table.userId, table.projectId),
    index("project_task_session_idx").on(table.sessionId),
    index("project_task_agent_key_idx").on(table.sessionId, table.agentTaskKey),
  ]
);

export const taskDependencies = sqliteTable(
  "task_dependency",
  {
    blockerId: text("blocker_id").notNull().references(() => projectTasks.id, { onDelete: "cascade" }),
    blockedId: text("blocked_id").notNull().references(() => projectTasks.id, { onDelete: "cascade" }),
  },
  (table) => [
    primaryKey({ columns: [table.blockerId, table.blockedId] }),
    index("task_dep_blocker_idx").on(table.blockerId),
    index("task_dep_blocked_idx").on(table.blockedId),
  ]
);

export const notificationEvents = sqliteTable(
  "notification_event",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    sessionName: text("session_name"),
    type: text("type").$type<NotificationType>().notNull(),
    severity: text("severity").$type<NotificationSeverity>().notNull().default("passive"),
    title: text("title").notNull(),
    body: text("body"),
    coalesceKey: text("coalesce_key"),
    count: integer("count").notNull().default(1),
    meta: text("meta", { mode: "json" }).$type<NotificationMeta | null>(),
    readAt: integer("read_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("notification_event_user_created_idx").on(table.userId, table.createdAt),
    index("notification_event_user_read_idx").on(table.userId, table.readAt),
    index("notification_event_coalesce_idx").on(table.userId, table.sessionId, table.coalesceKey, table.readAt),
  ]
);

export const pushTokens = sqliteTable(
  "push_token",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    fcmToken: text("fcm_token").notNull(),
    platform: text("platform").$type<"android" | "ios">().notNull(),
    deviceId: text("device_id"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("push_token_user_idx").on(table.userId),
    uniqueIndex("push_token_fcm_token_idx").on(table.fcmToken),
  ]
);

export const notificationPreferences = sqliteTable(
  "notification_preferences",
  {
    userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }),
    pushByType: text("push_by_type", { mode: "json" }).$type<Record<string, boolean>>().notNull().default({}),
    mutedSessionIds: text("muted_session_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
    quietHoursStart: integer("quiet_hours_start"),
    quietHoursEnd: integer("quiet_hours_end"),
    minPushSeverity: text("min_push_severity").$type<NotificationSeverity>().notNull().default("actionable"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const agentPeerMessages = sqliteTable(
  "agent_peer_message",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    projectId: text("project_id").notNull(),
    fromSessionId: text("from_session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    fromSessionName: text("from_session_name").notNull(),
    toSessionId: text("to_session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    isUserMessage: integer("is_user_message", { mode: "boolean" }).notNull().default(false),
    channelId: text("channel_id").references(() => channels.id, { onDelete: "set null" }),
    parentMessageId: text("parent_message_id"),
    replyCount: integer("reply_count").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("peer_message_project_created_idx").on(table.projectId, table.createdAt),
    index("peer_message_to_session_idx").on(table.toSessionId),
    index("peer_message_channel_created_idx").on(table.channelId, table.createdAt),
    index("peer_message_parent_idx").on(table.parentMessageId),
  ]
);

export const channelGroups = sqliteTable(
  "channel_group",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    position: integer("position").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("channel_group_project_idx").on(table.projectId),
    uniqueIndex("channel_group_project_name_idx").on(table.projectId, table.name),
  ]
);

export const channels = sqliteTable(
  "channel",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    groupId: text("group_id").notNull().references(() => channelGroups.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    displayName: text("display_name").notNull(),
    type: text("type").$type<ChannelType>().notNull().default("public"),
    topic: text("topic"),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    createdBySessionId: text("created_by_session_id"),
    lastMessageAt: integer("last_message_at", { mode: "timestamp_ms" }),
    messageCount: integer("message_count").notNull().default(0),
    archivedAt: integer("archived_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("channel_project_idx").on(table.projectId),
    index("channel_group_idx").on(table.groupId),
    uniqueIndex("channel_project_name_idx").on(table.projectId, table.name),
  ]
);

export const channelReadState = sqliteTable(
  "channel_read_state",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    channelId: text("channel_id").notNull().references(() => channels.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    lastReadMessageId: text("last_read_message_id"),
    lastReadAt: integer("last_read_at", { mode: "timestamp_ms" }),
  },
  (table) => [
    uniqueIndex("channel_read_state_unique_idx").on(table.channelId, table.userId),
    index("channel_read_state_user_idx").on(table.userId),
  ]
);

export const systemUpdateCache = sqliteTable(
  "system_update_cache",
  {
    id: text("id").primaryKey().default("singleton"),
    lastChecked: integer("last_checked", { mode: "timestamp_ms" }),
    cachedReleaseJson: text("cached_release_json"),
    deploymentStateJson: text("deployment_state_json"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const litellmConfig = sqliteTable(
  "litellm_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
    autoStart: integer("auto_start", { mode: "boolean" }).notNull().default(true),
    port: integer("port").notNull().default(4000),
    masterKey: text("master_key"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  }
);

export const litellmModels = sqliteTable(
  "litellm_model",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    modelName: text("model_name").notNull(),
    provider: text("provider").notNull(),
    litellmModel: text("litellm_model").notNull(),
    apiBase: text("api_base"),
    encryptedApiKey: text("encrypted_api_key"),
    keyPrefix: text("key_prefix"),
    extraHeaders: text("extra_headers"),
    priority: integer("priority").notNull().default(0),
    paused: integer("paused", { mode: "boolean" }).notNull().default(false),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("litellm_model_user_idx").on(table.userId),
  ]
);

export const projectGroups = sqliteTable(
  "project_group",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    parentGroupId: text("parent_group_id").references((): AnySQLiteColumn => projectGroups.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    collapsed: integer("collapsed", { mode: "boolean" }).notNull().default(false),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("project_group_user_idx").on(table.userId),
    index("project_group_parent_idx").on(table.parentGroupId),
  ]
);

export const projects = sqliteTable(
  "project",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    groupId: text("group_id").references(() => projectGroups.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    collapsed: integer("collapsed", { mode: "boolean" }).notNull().default(false),
    sortOrder: integer("sort_order").notNull().default(0),
    isAutoCreated: integer("is_auto_created", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("project_user_idx").on(table.userId),
    index("project_group_idx").on(table.groupId),
  ]
);

export const claudeAccounts = sqliteTable(
  "claude_account",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    profileId: text("profile_id").notNull().unique().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    accountKind: text("account_kind").$type<ClaudeAccountKind>().notNull().default("subscription"),
    credentialMode: text("credential_mode"),
    emailAddress: text("email_address"),
    organizationName: text("organization_name"),
    rateLimitTier: text("rate_limit_tier"),
    apiKeyPrefix: text("api_key_prefix"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("claude_account_profile_idx").on(table.profileId),
    index("claude_account_user_idx").on(table.userId),
  ]
);

export const claudeUsageLimitStates = sqliteTable(
  "claude_usage_limit_state",
  {
    profileId: text("profile_id").primaryKey().references(() => agentProfiles.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    limitStatus: text("limit_status").$type<ClaudeLimitStatus>().notNull().default("unknown"),
    window5hPct: integer("window_5h_pct"),
    window7dPct: integer("window_7d_pct"),
    resetAt5h: integer("reset_at_5h", { mode: "timestamp_ms" }),
    resetAt7d: integer("reset_at_7d", { mode: "timestamp_ms" }),
    effectiveResetAt: integer("effective_reset_at", { mode: "timestamp_ms" }),
    detectionSource: text("detection_source").$type<UsageDetectionSource>(),
    lastCheckedAt: integer("last_checked_at", { mode: "timestamp_ms" }),
    lastPolledAt: integer("last_polled_at", { mode: "timestamp_ms" }),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("claude_usage_limit_user_status_idx").on(table.userId, table.limitStatus),
    index("claude_usage_limit_user_idx").on(table.userId),
  ]
);

export const claudeProfilePools = sqliteTable(
  "claude_profile_pool",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("claude_profile_pool_user_idx").on(table.userId),
  ]
);

export const claudeProfilePoolMembers = sqliteTable(
  "claude_profile_pool_member",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    poolId: text("pool_id").notNull().references(() => claudeProfilePools.id, { onDelete: "cascade" }),
    profileId: text("profile_id").notNull().references(() => agentProfiles.id, { onDelete: "cascade" }),
    priority: integer("priority").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("claude_pool_member_pool_profile_unique").on(table.poolId, table.profileId),
    index("claude_pool_member_pool_priority_idx").on(table.poolId, table.priority),
    index("claude_pool_member_profile_idx").on(table.profileId),
  ]
);

export const nodePreferences = sqliteTable(
  "node_preferences",
  {
    id: text("id").primaryKey(),
    ownerId: text("owner_id").notNull(),
    ownerType: text("owner_type", { enum: ["group","project"] }).notNull(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    defaultWorkingDirectory: text("default_working_directory"),
    defaultShell: text("default_shell"),
    startupCommand: text("startup_command"),
    theme: text("theme"),
    fontSize: integer("font_size"),
    fontFamily: text("font_family"),
    githubRepoId: text("github_repo_id"),
    localRepoPath: text("local_repo_path"),
    defaultAgentProvider: text("default_agent_provider"),
    agentProviderSettings: text("agent_provider_settings", { mode: "json" }),
    environmentVars: text("environment_vars", { mode: "json" }),
    pinnedFiles: text("pinned_files", { mode: "json" }),
    gitIdentityName: text("git_identity_name"),
    gitIdentityEmail: text("git_identity_email"),
    isSensitive: integer("is_sensitive", { mode: "boolean" }).notNull().default(false),
    claudeProfilePoolId: text("claude_profile_pool_id"),
    claudeAutoRelaunchMode: text("claude_auto_relaunch_mode").$type<ClaudeAutoRelaunchMode>(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("node_pref_owner_idx").on(table.ownerId, table.ownerType),
    uniqueIndex("node_pref_owner_user_idx").on(table.ownerId, table.ownerType, table.userId),
  ]
);

export const projectSecretsConfig = sqliteTable(
  "project_secrets_config",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    providerConfig: text("provider_config", { mode: "json" }).notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    lastFetchedAt: integer("last_fetched_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("project_secrets_project_user_idx").on(table.projectId, table.userId),
  ]
);

export const projectGitHubAccountLinks = sqliteTable(
  "project_github_account_link",
  {
    projectId: text("project_id").primaryKey().references(() => projects.id, { onDelete: "cascade" }),
    providerAccountId: text("provider_account_id").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("project_gh_link_account_idx").on(table.providerAccountId),
  ]
);

export const projectProfileLinks = sqliteTable(
  "project_profile_link",
  {
    projectId: text("project_id").primaryKey().references(() => projects.id, { onDelete: "cascade" }),
    profileId: text("profile_id").notNull().references(() => agentProfiles.id, { onDelete: "cascade" }),
    poolId: text("pool_id").references(() => claudeProfilePools.id, { onDelete: "set null" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("project_profile_link_profile_idx").on(table.profileId),
  ]
);

export const projectRepositories = sqliteTable(
  "project_repository",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    repositoryId: text("repository_id").notNull().references(() => githubRepositories.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("project_repo_project_user_idx").on(table.projectId, table.userId),
    index("project_repo_user_idx").on(table.userId),
  ]
);

export const sshConnections = sqliteTable(
  "ssh_connection",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    host: text("host").notNull(),
    port: integer("port").notNull().default(22),
    username: text("username").notNull(),
    authType: text("auth_type", { enum: ["key","agent","password","system"] }).notNull(),
    hasPassphrase: integer("has_passphrase", { mode: "boolean" }).notNull().default(false),
    passwordEnc: text("password_enc"),
    knownHostsPolicy: text("known_hosts_policy", { enum: ["strict","accept-new","no"] }).notNull().default("accept-new"),
    extraOptions: text("extra_options", { mode: "json" }).$type<string[]>(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("ssh_connection_user_project_idx").on(table.userId, table.projectId),
  ]
);

export const triggerConfigs = sqliteTable(
  "trigger_config",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    githubRepoId: text("github_repo_id").references(() => githubRepositories.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    kind: text("kind").$type<TriggerKind>().notNull(),
    filter: text("filter").notNull().default("{}"),
    agentProvider: text("agent_provider").notNull().default("claude"),
    agentFlags: text("agent_flags").notNull().default("[]"),
    promptTemplate: text("prompt_template").notNull(),
    worktreeType: text("worktree_type"),
    profileId: text("profile_id").references(() => agentProfiles.id, { onDelete: "set null" }),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("trigger_config_user_idx").on(table.userId),
    index("trigger_config_repo_idx").on(table.githubRepoId),
  ]
);

export const agentSchedules = sqliteTable(
  "agent_schedule",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    agentProvider: text("agent_provider").notNull().default("claude"),
    agentFlags: text("agent_flags").notNull().default("[]"),
    prompt: text("prompt").notNull(),
    worktreeType: text("worktree_type"),
    baseBranch: text("base_branch"),
    profileId: text("profile_id").references(() => agentProfiles.id, { onDelete: "set null" }),
    scheduleType: text("schedule_type").$type<ScheduleType>().notNull().default("recurring"),
    cronExpression: text("cron_expression"),
    scheduledAt: integer("scheduled_at", { mode: "timestamp_ms" }),
    timezone: text("timezone").notNull().default("America/Los_Angeles"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    status: text("status").$type<ScheduleStatus>().notNull().default("active"),
    maxRetries: integer("max_retries").notNull().default(0),
    nextRunAt: integer("next_run_at", { mode: "timestamp_ms" }),
    lastRunAt: integer("last_run_at", { mode: "timestamp_ms" }),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_schedule_user_idx").on(table.userId),
    index("agent_schedule_next_run_idx").on(table.enabled, table.nextRunAt),
  ]
);

export const agentRuns = sqliteTable(
  "agent_run",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    scheduleId: text("schedule_id").references(() => agentSchedules.id, { onDelete: "set null" }),
    triggerConfigId: text("trigger_config_id").references(() => triggerConfigs.id, { onDelete: "set null" }),
    source: text("source").$type<AgentRunSource>().notNull(),
    agentProvider: text("agent_provider").notNull(),
    agentFlags: text("agent_flags").notNull().default("[]"),
    profileId: text("profile_id").references(() => agentProfiles.id, { onDelete: "set null" }),
    prompt: text("prompt").notNull(),
    sessionId: text("session_id").references(() => terminalSessions.id, { onDelete: "set null" }),
    headSha: text("head_sha"),
    status: text("status").$type<AgentRunStatus>().notNull().default("pending"),
    errorMessage: text("error_message"),
    startedAt: integer("started_at", { mode: "timestamp_ms" }),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_run_user_idx").on(table.userId),
    index("agent_run_schedule_idx").on(table.scheduleId),
    index("agent_run_trigger_idx").on(table.triggerConfigId),
    index("agent_run_status_idx").on(table.status),
    uniqueIndex("agent_run_trigger_head_idx").on(table.triggerConfigId, table.headSha),
  ]
);

export const triggerEvents = sqliteTable(
  "trigger_event",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    triggerConfigId: text("trigger_config_id").notNull().references(() => triggerConfigs.id, { onDelete: "cascade" }),
    eventKind: text("event_kind").notNull(),
    action: text("action"),
    headSha: text("head_sha"),
    matched: integer("matched", { mode: "boolean" }).notNull().default(false),
    runId: text("run_id").references(() => agentRuns.id, { onDelete: "set null" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("trigger_event_config_idx").on(table.triggerConfigId),
  ]
);

export const webhookDeliveries = sqliteTable(
  "webhook_delivery",
  {
    deliveryId: text("delivery_id").primaryKey(),
    eventKind: text("event_kind").notNull(),
    receivedAt: integer("received_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("webhook_delivery_received_idx").on(table.receivedAt),
  ]
);

export const crownRuns = sqliteTable(
  "crown_run",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    prompt: text("prompt").notNull(),
    agentProvider: text("agent_provider").notNull().default("claude"),
    candidateCount: integer("candidate_count").notNull(),
    judgeModel: text("judge_model"),
    baseBranch: text("base_branch"),
    status: text("status").$type<CrownRunStatus>().notNull().default("running"),
    winnerCandidateId: text("winner_candidate_id"),
    crownReason: text("crown_reason"),
    prUrl: text("pr_url"),
    errorMessage: text("error_message"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("crown_run_user_idx").on(table.userId),
  ]
);

export const crownCandidates = sqliteTable(
  "crown_candidate",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    crownRunId: text("crown_run_id").notNull().references(() => crownRuns.id, { onDelete: "cascade" }),
    runId: text("run_id").references(() => agentRuns.id, { onDelete: "set null" }),
    branch: text("branch").notNull(),
    worktreePath: text("worktree_path"),
    diff: text("diff"),
    diffStats: text("diff_stats"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("crown_candidate_run_idx").on(table.crownRunId),
  ]
);

export const messageDelivery = sqliteTable(
  "message_delivery",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    messageId: text("message_id").notNull().references(() => agentPeerMessages.id, { onDelete: "cascade" }),
    toSessionId: text("to_session_id").notNull().references(() => terminalSessions.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull(),
    state: text("state").$type<"pending" | "delivered" | "acked">().notNull().default("pending"),
    channelType: text("channel_kind").$type<"mcp_push" | "poll" | null>(),
    deliveredAt: integer("delivered_at", { mode: "timestamp_ms" }),
    ackedAt: integer("acked_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("message_delivery_msg_session_idx").on(table.messageId, table.toSessionId),
    index("message_delivery_session_state_idx").on(table.toSessionId, table.state, table.createdAt),
  ]
);

export const channelSubscription = sqliteTable(
  "channel_subscription",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    channelId: text("channel_id").notNull().references(() => channels.id, { onDelete: "cascade" }),
    sessionId: text("session_id").notNull().references(() => terminalSessions.id, { onDelete: "cascade" }),
    mode: text("mode").$type<"auto_deliver" | "direct_only">().notNull().default("auto_deliver"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    uniqueIndex("channel_subscription_unique_idx").on(table.channelId, table.sessionId),
  ]
);

export const agentWorkContext = sqliteTable(
  "agent_work_context",
  {
    sessionId: text("session_id").primaryKey().references(() => terminalSessions.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull(),
    branch: text("branch"),
    worktreePath: text("worktree_path"),
    activityStatus: text("activity_status"),
    claimedIssueId: text("claimed_issue_id"),
    claimedIssueTitle: text("claimed_issue_title"),
    joinConfidence: text("join_confidence").$type<"branch" | "project" | "none">(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("agent_work_context_project_idx").on(table.projectId),
  ]
);

export const peerInstances = sqliteTable(
  "peer_instance",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    baseUrl: text("base_url").notNull(),
    encryptedApiKey: text("encrypted_api_key").notNull(),
    cfAccessClientId: text("cf_access_client_id"),
    encryptedCfAccessSecret: text("encrypted_cf_access_secret"),
    capabilities: text("capabilities"),
    lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("peer_instance_user_idx").on(table.userId),
    uniqueIndex("peer_instance_user_name_unique").on(table.userId, table.name),
  ]
);

export const migrationJobs = sqliteTable(
  "migration_job",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    peerInstanceId: text("peer_instance_id").references(() => peerInstances.id, { onDelete: "set null" }),
    status: text("status").$type<MigrationJobStatus>().notNull().default("pending"),
    workingTreeMode: text("working_tree_mode").$type<MigrationWorkingTreeMode>().notNull().default("full_tar"),
    includeDotEnv: integer("include_dot_env", { mode: "boolean" }).notNull().default(true),
    includeAgentCreds: integer("include_agent_creds", { mode: "boolean" }).notNull().default(true),
    includeSshKeys: integer("include_ssh_keys", { mode: "boolean" }).notNull().default(false),
    includeAgentSettings: integer("include_agent_settings", { mode: "boolean" }).notNull().default(true),
    includeChannelHistory: integer("include_channel_history", { mode: "boolean" }).notNull().default(false),
    removeSourceAfterVerify: integer("remove_source_after_verify", { mode: "boolean" }).notNull().default(false),
    sizeEstimateBytes: integer("size_estimate_bytes"),
    bytesTransferred: integer("bytes_transferred").notNull().default(0),
    destProjectId: text("dest_project_id"),
    bundleManifestJson: text("bundle_manifest_json"),
    conflictReportJson: text("conflict_report_json"),
    errorMessage: text("error_message"),
    startedAt: integer("started_at", { mode: "timestamp_ms" }),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("migration_job_user_idx").on(table.userId),
    index("migration_job_project_idx").on(table.projectId),
    index("migration_job_user_status_idx").on(table.userId, table.status),
  ]
);

export const migrationImports = sqliteTable(
  "migration_import",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    sourceInstanceUrl: text("source_instance_url").notNull(),
    status: text("status").$type<MigrationImportStatus>().notNull().default("staged"),
    stagingDir: text("staging_dir").notNull(),
    chunksReceived: integer("chunks_received").notNull().default(0),
    totalChunks: integer("total_chunks"),
    importedProjectId: text("imported_project_id"),
    manifestJson: text("manifest_json"),
    optionsJson: text("options_json").notNull().default("{}"),
    errorMessage: text("error_message"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("migration_import_status_idx").on(table.status),
    index("migration_import_user_idx").on(table.userId),
  ]
);
