// AUTO-GENERATED by scripts/codegen-schema.ts — DO NOT EDIT.
// Edit schema.def.ts and run `bun run db:codegen`.
// Runtime dialect switch: consumers import { table } from "@/db/schema" and
// transparently receive the SQLite or Postgres table object depending on
// DATABASE_URL. The cast to `typeof sqliteSchema` keeps consumer TYPES stable —
// $inferSelect/$inferInsert are identical across dialects by construction.
import * as sqliteSchema from "./schema.sqlite";
import * as pgSchema from "./schema.pg";
import { isPostgres } from "./is-postgres";

const active = (isPostgres() ? pgSchema : sqliteSchema) as typeof sqliteSchema;

export const {
  supervisorUser,
  instance,
  registeredStorageTarget,
  instanceAuditLog,
  instanceSeed,
  warmPool,
  users,
  accounts,
  sessions,
  verificationTokens,
} = active;

// Brand types (re-exported from the standalone module so `@/db/schema`
// consumers keep importing them from here, unchanged).
export type { SupervisorRole, InstanceStatus, StorageTargetKind } from "./schema-types";

// Inferred row types for convenience in services / route handlers. Derived
// from the ACTIVE dialect's tables, so they are identical across backends.
export type SupervisorUserRow = typeof supervisorUser.$inferSelect;
export type InstanceRow = typeof instance.$inferSelect;
export type RegisteredStorageTargetRow = typeof registeredStorageTarget.$inferSelect;
export type InstanceAuditLogRow = typeof instanceAuditLog.$inferSelect;
export type InstanceSeedRow = typeof instanceSeed.$inferSelect;
