// AUTO-GENERATED by scripts/codegen-schema.ts — DO NOT EDIT.
// Edit schema.def.ts and run `bun run db:codegen`.

import { pgTable, text, integer, boolean, timestamp, index, primaryKey } from "drizzle-orm/pg-core";
import type { AdapterAccountType } from "next-auth/adapters";
import type {
  SupervisorRole,
  InstanceStatus,
  StorageTargetKind,
} from "./schema-types";

export const supervisorUser = pgTable(
  "supervisor_user",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    email: text("email").notNull().unique(),
    role: text("role").$type<SupervisorRole>().notNull().default("viewer"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date()),
  }
);

export const instance = pgTable(
  "instance",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    slug: text("slug").notNull().unique(),
    displayName: text("display_name").notNull(),
    ownerId: text("owner_id").notNull().references(() => supervisorUser.id, { onDelete: "restrict" }),
    status: text("status").$type<InstanceStatus>().notNull().default("requested"),
    errorMessage: text("error_message"),
    namespace: text("namespace").notNull(),
    imageTag: text("image_tag"),
    baseUrl: text("base_url"),
    storageTargetId: text("storage_target_id"),
    storageConfigSnapshot: text("storage_config_snapshot"),
    dbConfigSnapshot: text("db_config_snapshot"),
    cpuRequest: text("cpu_request"),
    cpuLimit: text("cpu_limit"),
    memRequest: text("mem_request"),
    memLimit: text("mem_limit"),
    storageRequest: text("storage_request"),
    lastReconciledAt: timestamp("last_reconciled_at", { withTimezone: true, mode: "date" }),
    provisionedAt: timestamp("provisioned_at", { withTimezone: true, mode: "date" }),
    suspendedAt: timestamp("suspended_at", { withTimezone: true, mode: "date" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date()),
  },
  (table) => [
    index("instance_owner_idx").on(table.ownerId),
    index("instance_status_idx").on(table.status),
  ]
);

export const registeredStorageTarget = pgTable(
  "registered_storage_target",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull().unique(),
    kind: text("kind").$type<StorageTargetKind>().notNull(),
    config: text("config").notNull(),
    resiliencyNote: text("resiliency_note"),
    isDefault: boolean("is_default").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()),
  }
);

export const instanceAuditLog = pgTable(
  "instance_audit_log",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    instanceId: text("instance_id").notNull().references(() => instance.id, { onDelete: "cascade" }),
    actorId: text("actor_id"),
    actorEmail: text("actor_email"),
    action: text("action").notNull(),
    previousStatus: text("previous_status").$type<InstanceStatus>(),
    newStatus: text("new_status").$type<InstanceStatus>(),
    metadata: text("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().$defaultFn(() => new Date()),
  },
  (table) => [
    index("instance_audit_log_instance_idx").on(table.instanceId),
  ]
);

export const instanceSeed = pgTable(
  "instance_seed",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    instanceId: text("instance_id").notNull().unique().references(() => instance.id, { onDelete: "cascade" }),
    authorizedEmails: text("authorized_emails"),
    jobDispatched: boolean("job_dispatched").notNull().default(false),
    jobName: text("job_name"),
    completedAt: timestamp("completed_at", { withTimezone: true, mode: "date" }),
  }
);

export const users = pgTable(
  "user",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name"),
    email: text("email").unique(),
    emailVerified: timestamp("emailVerified", { withTimezone: true, mode: "date" }),
    image: text("image"),
  }
);

export const accounts = pgTable(
  "account",
  {
    userId: text("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (table) => [
    primaryKey({ columns: [table.provider, table.providerAccountId] }),
    index("account_user_idx").on(table.userId),
  ]
);

export const sessions = pgTable(
  "session",
  {
    sessionToken: text("sessionToken").primaryKey(),
    userId: text("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  }
);

export const verificationTokens = pgTable(
  "verificationToken",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.identifier, table.token] }),
  ]
);
