/**
 * Schema codegen — single source of truth in src/db/schema.def.ts.
 *
 * Reads the neutral SchemaDefinition and emits THREE files:
 *   1. src/db/schema.sqlite.ts — drizzle sqlite-core tables (behavior-identical
 *      to the historical hand-written schema.ts).
 *   2. src/db/schema.pg.ts     — drizzle pg-core tables (structurally identical).
 *   3. src/db/schema.ts        — a barrel that re-exports the active dialect at
 *      runtime so the ~83 `@/db/schema` consumers keep working unchanged.
 *
 * Run with: `bun run db:codegen`.
 *
 * The structural snapshot (scripts/schema-structural-snapshot.ts) proves the
 * generated SQLite schema deep-equals the original — the acceptance bar for
 * "SQLite behavior unchanged".
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type {
  SchemaDefinition,
  TableDefinition,
  ColumnDefinition,
  ColumnDefault,
} from "../src/db/schema.def";

const ROOT = resolve(import.meta.dirname, "..");
const DEF_PATH = resolve(ROOT, "src/db/schema.def.ts");

const BANNER =
  "// AUTO-GENERATED by scripts/codegen-schema.ts — DO NOT EDIT.\n" +
  "// Edit schema.def.ts and run `bun run db:codegen`.\n";

/** Extract the verbatim type-import block from the top of schema.def.ts. */
function extractTypeImports(defSource: string): string {
  const lines = defSource.split("\n");
  const imports: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("import ")) {
      imports.push(line);
    }
    // Stop once we reach the first type/interface declaration.
    if (trimmed.startsWith("export type") || trimmed.startsWith("export interface")) {
      break;
    }
  }
  return imports.join("\n");
}

// ---------------------------------------------------------------------------
// Default emission (shared across dialects — same TS at runtime).
// ---------------------------------------------------------------------------
function emitDefaultChain(def: ColumnDefault): string {
  switch (def.kind) {
    case "value":
      return `.default(${def.value})`;
    case "fn":
      return def.fn === "uuid"
        ? `.$defaultFn(() => crypto.randomUUID())`
        : `.$defaultFn(() => new Date())`;
    case "raw":
      return `.$defaultFn(() => ${def.expr})`;
  }
}

/** Common modifier chain (notNull/unique/default + $type brand) shared by both dialects. */
function emitSharedModifiers(col: ColumnDefinition): string {
  let chain = "";
  if (col.typeBrand) chain += `.$type<${col.typeBrand}>()`;
  if (col.notNull) chain += `.notNull()`;
  if (col.unique) chain += `.unique()`;
  if (col.default) chain += emitDefaultChain(col.default);
  return chain;
}

// ---------------------------------------------------------------------------
// SQLite column builder
// ---------------------------------------------------------------------------
function sqliteColumnBuilder(col: ColumnDefinition): string {
  const name = JSON.stringify(col.dbName);
  switch (col.kind) {
    case "text":
      return col.enumValues
        ? `text(${name}, { enum: ${JSON.stringify(col.enumValues)} })`
        : `text(${name})`;
    case "json":
      return `text(${name}, { mode: "json" })`;
    case "integer":
      return `integer(${name})`;
    case "boolean":
      return `integer(${name}, { mode: "boolean" })`;
    case "timestampMs":
      return `integer(${name}, { mode: "timestamp_ms" })`;
    case "timestampS":
      return `integer(${name}, { mode: "timestamp" })`;
  }
}

// ---------------------------------------------------------------------------
// Postgres column builder
// ---------------------------------------------------------------------------
function pgColumnBuilder(col: ColumnDefinition): string {
  const name = JSON.stringify(col.dbName);
  switch (col.kind) {
    case "text":
      return col.enumValues
        ? `text(${name}, { enum: ${JSON.stringify(col.enumValues)} })`
        : `text(${name})`;
    case "json":
      return `jsonb(${name})`;
    case "integer":
      return `integer(${name})`;
    case "boolean":
      return `boolean(${name})`;
    case "timestampMs":
    case "timestampS":
      return `timestamp(${name}, { withTimezone: true, mode: "date" })`;
  }
}

// ---------------------------------------------------------------------------
// References emission (dialect-specific only for the self-ref cast type).
// ---------------------------------------------------------------------------
function emitReferences(col: ColumnDefinition, anyColumnType: string): string {
  const ref = col.references;
  if (!ref) return "";
  const opts = ref.onDelete ? `, { onDelete: ${JSON.stringify(ref.onDelete)} }` : "";
  if (ref.selfRef) {
    // Self-FK: drizzle needs an explicit return-type annotation to break the
    // circular type inference (the table references its own column).
    return `.references((): ${anyColumnType} => ${ref.table}.${ref.column}${opts})`;
  }
  return `.references(() => ${ref.table}.${ref.column}${opts})`;
}

// ---------------------------------------------------------------------------
// Column line
// ---------------------------------------------------------------------------
function emitColumnLine(
  col: ColumnDefinition,
  builder: (c: ColumnDefinition) => string,
  anyColumnType: string
): string {
  let line = `    ${col.field}: ${builder(col)}`;
  if (col.primaryKey) line += `.primaryKey()`;
  line += emitSharedModifiers(col);
  line += emitReferences(col, anyColumnType);
  line += ",";
  return line;
}

// ---------------------------------------------------------------------------
// Table extras callback (indexes + composite PK)
// ---------------------------------------------------------------------------
function emitExtras(table: TableDefinition, dialect: "sqlite" | "pg"): string {
  const lines: string[] = [];
  if (table.primaryKey) {
    const cols = table.primaryKey.map((c) => `table.${c}`).join(", ");
    lines.push(`    primaryKey({ columns: [${cols}] }),`);
  }
  for (const idx of table.indexes ?? []) {
    // Per-index dialect skip: a column-level `unique` auto-creates an
    // identically-named backing index in Postgres, so emitting an explicit
    // index of the same name would collide (42P07). SQLite tolerates both, and
    // the live SQLite DBs already carry the explicit index, so it stays there.
    if (dialect === "pg" && idx.omitForPg) continue;
    const fn = idx.unique ? "uniqueIndex" : "index";
    const cols = idx.columns.map((c) => `table.${c}`).join(", ");
    lines.push(`    ${fn}(${JSON.stringify(idx.name)}).on(${cols}),`);
  }
  if (lines.length === 0) return "";
  return `,\n  (table) => [\n${lines.join("\n")}\n  ]`;
}

// ---------------------------------------------------------------------------
// Table emission
// ---------------------------------------------------------------------------
function emitTable(
  table: TableDefinition,
  tableFn: string,
  builder: (c: ColumnDefinition) => string,
  anyColumnType: string,
  dialect: "sqlite" | "pg"
): string {
  const cols = table.columns
    .map((c) => emitColumnLine(c, builder, anyColumnType))
    .join("\n");
  const extras = emitExtras(table, dialect);
  return `export const ${table.exportName} = ${tableFn}(\n  ${JSON.stringify(
    table.sqlName
  )},\n  {\n${cols}\n  }${extras}\n);`;
}

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------
function generateSqlite(schema: SchemaDefinition, typeImports: string): string {
  const imports = [
    BANNER,
    `import { sqliteTable, text, integer, index, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";`,
    `import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";`,
    typeImports,
    "",
  ].join("\n");
  const tables = schema
    .map((t) => emitTable(t, "sqliteTable", sqliteColumnBuilder, "AnySQLiteColumn", "sqlite"))
    .join("\n\n");
  return `${imports}\n${tables}\n`;
}

function generatePg(schema: SchemaDefinition, typeImports: string): string {
  const imports = [
    BANNER,
    `import { pgTable, text, integer, boolean, timestamp, jsonb, index, uniqueIndex, primaryKey } from "drizzle-orm/pg-core";`,
    `import type { AnyPgColumn } from "drizzle-orm/pg-core";`,
    typeImports,
    "",
  ].join("\n");
  const tables = schema
    .map((t) => emitTable(t, "pgTable", pgColumnBuilder, "AnyPgColumn", "pg"))
    .join("\n\n");
  return `${imports}\n${tables}\n`;
}

function generateBarrel(schema: SchemaDefinition): string {
  const names = schema.map((t) => t.exportName);
  // Emit the destructuring list one-per-line for readability + stable diffs.
  const destructure = names.map((n) => `  ${n},`).join("\n");
  return `${BANNER}// Runtime dialect switch: consumers import { table } from "@/db/schema" and
// transparently receive the SQLite or Postgres table object depending on
// DATABASE_URL. The cast to \`typeof sqliteSchema\` keeps consumer TYPES stable —
// $inferSelect/$inferInsert are identical across dialects by construction.
import * as sqliteSchema from "./schema.sqlite";
import * as pgSchema from "./schema.pg";
import { isPostgres } from "./is-postgres";

const active = (isPostgres() ? pgSchema : sqliteSchema) as typeof sqliteSchema;

export const {
${destructure}
} = active;
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  const defSource = readFileSync(DEF_PATH, "utf8");
  const typeImports = extractTypeImports(defSource);

  const mod: { schema: SchemaDefinition } = await import(
    pathToFileURL(DEF_PATH).href
  );
  const schema = mod.schema;

  const sqliteOut = generateSqlite(schema, typeImports);
  const pgOut = generatePg(schema, typeImports);
  const barrelOut = generateBarrel(schema);

  writeFileSync(resolve(ROOT, "src/db/schema.sqlite.ts"), sqliteOut, "utf8");
  writeFileSync(resolve(ROOT, "src/db/schema.pg.ts"), pgOut, "utf8");
  writeFileSync(resolve(ROOT, "src/db/schema.ts"), barrelOut, "utf8");

  const colCount = schema.reduce((s, t) => s + t.columns.length, 0);
  process.stdout.write(
    `Codegen complete: ${schema.length} tables, ${colCount} columns\n` +
      `  src/db/schema.sqlite.ts (${sqliteOut.length} bytes)\n` +
      `  src/db/schema.pg.ts     (${pgOut.length} bytes)\n` +
      `  src/db/schema.ts        (${barrelOut.length} bytes, barrel)\n`
  );
}

main().catch((err) => {
  process.stderr.write(String(err instanceof Error ? err.stack : err) + "\n");
  process.exit(1);
});
